{
 "title": "MAGN Forecast backup",
 "time": { "from": "now-3y-4M", "to": "now+2M" },
 "templating": {
  "list": [
   { "name": "sec_code", "label": "sec_code", "query": "SELECT seccode FROM securities" },
   { "name": "price_lag_months", "query": "0,1,1.25,1.5,1.75,2" },
   { "name": "forecast_IronSlab", "query": "244" },
   { "name": "forecast_PriceAverage", "query": "916" },
   {
    "name": "forecast_Slab",
    "query": "SELECT floor(sum(perc)+$forecast_IronSlab,1) as Slab\nFROM (\n      SELECT last_value(quarter) as q,\n             last_value(slab_cash_cost_structure.value) * last_value(financial_ratios.value) as perc\n      FROM slab_cash_cost_structure\n               LEFT JOIN financial_ratios ON\n              financial_ratios.quarter == slab_cash_cost_structure.quarter\n              and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\n      WHERE (structure == 'Pellets'\n   or structure == 'Iron ore & concentrate'\n   or structure == 'Metal scrap')\n        and indicator == 'Slab Cash cost (USD/t)'\n      GROUP BY structure)\nGROUP BY q\nORDER BY q"
   },
   { "name": "forecast_sales", "query": "3320" },
   { "name": "price_lag_weeks", "query": "13,15,17,18,19" }
  ]
 },
 "panels": [
  { "title": "TRANSAQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Price History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avgWeighted(close, volume) as price\nFROM $table\n\nWHERE\n    $timeFilter\n    and sec_code = '$sec_code'\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 604800) * 604800) * 1000 as t,\n    avgWeighted(close, volume) as price\nFROM default.candles\n\nWHERE\n    date >= toDateTime(1520176154) AND date <= toDateTime(1636038554)\n    and sec_code = '$sec_code'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "candles"
    }
   ]
  },
  { "title": "HIGHLIGHTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Динамика Выручки и EBITDA",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select quarter_name,\n       last_value(multiIf(equals(indicator,'CAPEX'), value, NULL)) as CAPEX,\n       last_value(multiIf(equals(indicator,'EBITDA'), value, NULL)) as EBITDA,\n       last_value(multiIf(equals(indicator,'Revenue'), value, NULL)) as Revenue\nfrom $table\ngroup by quarter_name, $dateCol\norder by $dateCol\nUNION ALL (SELECT 'Q2 2021' , 1 , 1, 1)\n",
     "rawQuery": "select quarter_name,\n       last_value(multiIf(equals(indicator,'CAPEX'), value, NULL)) as CAPEX,\n       last_value(multiIf(equals(indicator,'EBITDA'), value, NULL)) as EBITDA,\n       last_value(multiIf(equals(indicator,'Revenue'), value, NULL)) as Revenue\nfrom default.financial_highlights\ngroup by quarter_name, quarter\norder by quarter\nUNION ALL (SELECT 'Q2 2021' , 1 , 1, 1)",
     "round": "0s",
     "table": "financial_highlights"
    }
   ]
  },
  {
   "title": "Динамика Свободного денежного потока",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select quarter_name,\n       last_value(multiIf(equals(indicator,'Free-cash flow (FCF)'), value, NULL)) as FCF,\n       last_value(multiIf(equals(indicator,'Dividends paid'), value, NULL)) as Dividends\nfrom $table\ngroup by quarter_name,$dateCol\norder by $dateCol\n\n\n",
     "rawQuery": "select quarter_name,\n       last_value(multiIf(equals(indicator,'Free-cash flow (FCF)'), value, NULL)) as FCF,\n       last_value(multiIf(equals(indicator,'Dividends paid'), value, NULL)) as Dividends\nfrom default.financial_highlights\ngroup by quarter_name,quarter\norder by quarter",
     "round": "0s",
     "table": "financial_highlights"
    }
   ]
  },
  {
   "title": "Производственные показатели,  тыс. тон",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    production as p,\n    last_value(value) as v\nFROM $table\nWHERE has(array('Pig iron', 'Crude steel', 'Finished products, incl.', 'Premium products'), p) == 1\nGROUP BY q, p\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    production as p,\n    last_value(value) as v\nFROM default.productions\nWHERE has(array('Pig iron', 'Crude steel', 'Finished products, incl.', 'Premium products'), p) == 1\nGROUP BY q, p\nORDER BY q",
     "round": "0s",
     "table": "productions"
    }
   ]
  },
  {
   "title": "Консолидированные продажи по видам продукции,  тыс. тон",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select t, avg(LoadingRZD*1000) as \"Loading RZD avg\" FROM (SELECT $dateCol as t, last_value(value) as LoadingRZD FROM $table GROUP BY t\nUNION ALL (SELECT toDate(toStartOfMonth(date_add(month, -1, $dateCol))) as t, last_value(value) as LoadingRZD FROM $table GROUP BY t))\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "select t, avg(LoadingRZD*1000) as \"Loading RZD avg\" FROM (SELECT month as t, last_value(value) as LoadingRZD FROM default.loading_rzd GROUP BY t\nUNION ALL (SELECT toDate(toStartOfMonth(date_add(month, -1, month))) as t, last_value(value) as LoadingRZD FROM default.loading_rzd GROUP BY t))\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "loading_rzd"
    },
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as t,\n    last_value(value)*1000 as \"Loading RZD last\"\nFROM $table\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT\n    month as t,\n    last_value(value)*1000 as \"Loading RZD last\"\nFROM default.loading_rzd\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "loading_rzd"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    product as p,\n    last_value(value) as v\nFROM $table\nWHERE has(array('Premium products', 'Flat hot-rolled products', 'Long products'), p) == 1 and sec_code == '$sec_code'\nGROUP BY q, p\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    product as p,\n    last_value(value) as v\nFROM default.consolidated_sales_for_products\nWHERE has(array('Premium products', 'Flat hot-rolled products', 'Long products'), p) == 1 and sec_code == '$sec_code'\nGROUP BY q, p\nORDER BY q",
     "round": "0s",
     "table": "consolidated_sales_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(inv.value)*1000/last_value(prices.price)/4 as \"Inventories in HRC\"\nFROM $table as inv\nLEFT JOIN prices_for_products as prices ON prices.quarter == inv.quarter\nWHERE inv.indicator == 'Inventories' and prices.product == 'Flat hot-rolled products' and inv.sec_code == '$sec_code'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(inv.value)*1000/last_value(prices.price)/4 as \"Inventories in HRC\"\nFROM default.financial_ratios as inv\nLEFT JOIN prices_for_products as prices ON prices.quarter == inv.quarter\nWHERE inv.indicator == 'Inventories' and prices.product == 'Flat hot-rolled products' and inv.sec_code == '$sec_code'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "financial_ratios"
    }
   ]
  },
  {
   "title": "EBITDA/т и цена реализации металлопродукции USD/т",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (SELECT\n    $dateCol as q,\n    last_value(value) as \"EBITDA per tonne\"\nFROM $table\nWHERE indicator == 'EBITDA per tonne* (USD/t)'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 427))\nORDER BY q",
     "rawQuery": "SELECT * FROM (SELECT\n    quarter as q,\n    last_value(value) as \"EBITDA per tonne\"\nFROM default.financial_ratios\nWHERE indicator == 'EBITDA per tonne* (USD/t)'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 427))\nORDER BY q",
     "round": "0s",
     "table": "financial_ratios"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(value) as \"Slab cash-cost\"\nFROM $table\nWHERE indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q\nORDER BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , $forecast_Slab)",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as \"Slab cash-cost\"\nFROM default.financial_ratios\nWHERE indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q\nORDER BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 476.9)",
     "round": "0s",
     "table": "financial_ratios"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as ConsolidateWeightedAverage\nFROM $table\nWHERE product == 'Sales of finished products, including:'\nGROUP BY q\nORDER BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , $forecast_PriceAverage)",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as ConsolidateWeightedAverage\nFROM default.consolidated_prices_for_products\nWHERE product == 'Sales of finished products, including:'\nGROUP BY q\nORDER BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 906)",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    }
   ]
  },
  {
   "title": "Выручка расчетная и EBITDA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * FROM (\n    SELECT\n    $dateCol as q,\n    last_value(prices.price)*last_value(sales.value)/1000 as calculatedRevenue\nFROM $table as prices\nLEFT JOIN consolidated_sales_for_products as sales on (prices.sec_code == sales.sec_code and prices.quarter == sales.quarter)\nWHERE prices.product == 'Sales of finished products, including:' and sales.product == 'Sales of finished products, including:'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , $forecast_PriceAverage*$forecast_sales/1000 as Revenue))\nORDER BY q\n\n",
     "rawQuery": "select * FROM (\n    SELECT\n    quarter as q,\n    last_value(prices.price)*last_value(sales.value)/1000 as calculatedRevenue\nFROM default.consolidated_prices_for_products as prices\nLEFT JOIN consolidated_sales_for_products as sales on (prices.sec_code == sales.sec_code and prices.quarter == sales.quarter)\nWHERE prices.product == 'Sales of finished products, including:' and sales.product == 'Sales of finished products, including:'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 944*3320/1000 as Revenue))\nORDER BY q",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * FROM (SELECT\n    $dateCol as q,\n    last_value(value) as EBITDA\nFROM $table\nWHERE indicator == 'EBITDA' and sec_code == '$sec_code'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 444*$forecast_sales/1000 as EBITDA))\nORDER BY q\n",
     "rawQuery": "select * FROM (SELECT\n    quarter as q,\n    last_value(value) as EBITDA\nFROM default.financial_highlights\nWHERE indicator == 'EBITDA' and sec_code == '$sec_code'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 444*3320/1000 as EBITDA))\nORDER BY q",
     "round": "0s",
     "table": "financial_highlights"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * FROM (SELECT\n    $dateCol as q,\n    last_value(value) as Revenue\nFROM $table\nWHERE indicator == 'Revenue' and sec_code == '$sec_code'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , $forecast_PriceAverage*$forecast_sales*1.04/1000 as Revenue))\nORDER BY q\n",
     "rawQuery": "select * FROM (SELECT\n    quarter as q,\n    last_value(value) as Revenue\nFROM default.financial_highlights\nWHERE indicator == 'Revenue' and sec_code == '$sec_code'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 944*3320*1.04/1000 as Revenue))\nORDER BY q",
     "round": "0s",
     "table": "financial_highlights"
    }
   ]
  },
  { "title": "Production & Sales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Цены за тонну продукции",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as FlatHotRolled\nFROM $table\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as FlatHotRolled\nFROM default.prices_for_products\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as ConsolidateWeightedAverage\nFROM $table\nWHERE product == 'Sales of finished products, including:'\nGROUP BY q\nORDER BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , $forecast_PriceAverage)",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as ConsolidateWeightedAverage\nFROM default.consolidated_prices_for_products\nWHERE product == 'Sales of finished products, including:'\nGROUP BY q\nORDER BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 906)",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as ExportAverage\nFROM $table\nWHERE product == 'Export'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as ExportAverage\nFROM default.prices_for_products\nWHERE product == 'Export'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as ConsolidateFlatHotRolled\nFROM $table\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as ConsolidateFlatHotRolled\nFROM default.consolidated_prices_for_products\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    },
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(toStartOfQuarter(date_add(month, $price_lag_months, date))) as q,\n    avg(close) as HRC_FOB_CHINA\nFROM $table\n\nWHERE code == 'MHCc1'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    toDate(toStartOfQuarter(date_add(month, 4, date))) as q,\n    avg(close) as HRC_FOB_CHINA\nFROM default.stock_prices\n\nWHERE code == 'MHCc1'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    }
   ]
  },
  {
   "title": "Консолидированные продажи, ton",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    product,\n    last_value(value)\nFROM $table\nWHERE sec_code == '$sec_code' and has(array('Premium products, including:','Long products', 'Flat hot-rolled products'), product) == 1\nGROUP BY q, product\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    product,\n    last_value(value)\nFROM default.consolidated_sales_for_products\nWHERE sec_code == '$sec_code' and has(array('Premium products, including:','Long products', 'Flat hot-rolled products'), product) == 1\nGROUP BY q, product\nORDER BY q",
     "round": "0s",
     "table": "consolidated_sales_for_products"
    }
   ]
  },
  {
   "title": "Консолидированные цены продаж",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    product,\n    last_value(price)\nFROM $table\nWHERE sec_code == '$sec_code' and has(array('HVA products, including:','Long products', 'Flat hot-rolled products'), product) == 1\nGROUP BY q, product\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    product,\n    last_value(price)\nFROM default.consolidated_prices_for_products\nWHERE sec_code == '$sec_code' and has(array('HVA products, including:','Long products', 'Flat hot-rolled products'), product) == 1\nGROUP BY q, product\nORDER BY q",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as \"MMK HRC FOB CHINA\"\nFROM $table\nWHERE product == 'HRC FOB CHINA'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as \"MMK HRC FOB CHINA\"\nFROM default.fob_prices\nWHERE product == 'HRC FOB CHINA'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "fob_prices"
    }
   ]
  },
  {
   "title": "Динамика цен на г/к прокат в дол. США",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (\nSELECT\n    $dateCol as q,\n    last_value(price) as \"MMK HRC\"\nFROM $table\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 950))\nORDER BY q",
     "rawQuery": "SELECT * FROM (\nSELECT\n    quarter as q,\n    last_value(price) as \"MMK HRC\"\nFROM default.prices_for_products\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 950))\nORDER BY q",
     "round": "0s",
     "table": "prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(toStartOfQuarter(date_add(week, $price_lag_weeks, date))) as q,\n    avg(close) as \"HRC FOB CHINA\"\nFROM $table\nWHERE code == 'MHCc1'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    toDate(toStartOfQuarter(date_add(week, 18, date))) as q,\n    avg(close) as \"HRC FOB CHINA\"\nFROM default.stock_prices\nWHERE code == 'MHCc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (\nSELECT\n    $dateCol as q,\n    last_value(price) as \"Consolidate\"\nFROM $table\nWHERE product == 'Sales of finished products'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 980))\nORDER BY q\n",
     "rawQuery": "SELECT * FROM (\nSELECT\n    quarter as q,\n    last_value(price) as \"Consolidate\"\nFROM default.consolidated_prices_for_products\nWHERE product == 'Sales of finished products'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 980))\nORDER BY q",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as \"MMK HRC FOB CHINA\"\nFROM $table\nWHERE product == 'HRC FOB CHINA'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as \"MMK HRC FOB CHINA\"\nFROM default.fob_prices\nWHERE product == 'HRC FOB CHINA'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "fob_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as \"MMK HRC FOB BS\"\nFROM $table\nWHERE product == 'HRC FOB Black sea'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as \"MMK HRC FOB BS\"\nFROM default.fob_prices\nWHERE product == 'HRC FOB Black sea'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "fob_prices"
    }
   ]
  },
  { "title": "COS breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Структура затрат",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Other\nFROM $table\n\nWHERE structure == 'Other production costs'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Other\nFROM default.cost_of_sales_structure\n\nWHERE structure == 'Other production costs'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Services\nFROM $table\n\nWHERE structure == 'Services received'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Services\nFROM default.cost_of_sales_structure\n\nWHERE structure == 'Services received'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Depreciation\nFROM $table\n\nWHERE structure == 'Depreciation'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Depreciation\nFROM default.cost_of_sales_structure\n\nWHERE structure == 'Depreciation'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Labour\nFROM $table\n\nWHERE structure == 'Labour costs'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Labour\nFROM default.cost_of_sales_structure\n\nWHERE structure == 'Labour costs'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Material\nFROM $table\n\nWHERE structure == 'Material costs'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Material\nFROM default.cost_of_sales_structure\n\nWHERE structure == 'Material costs'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    }
   ]
  },
  {
   "title": "Затраты на материалы, USD mln",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Scrap\nFROM $table\nWHERE material == 'Metal scrap'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Scrap\nFROM default.material_cost_structure\nWHERE material == 'Metal scrap'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Pellets\nFROM $table\nWHERE material == 'Pellets'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Pellets\nFROM default.material_cost_structure\nWHERE material == 'Pellets'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as IronOre\nFROM $table\nWHERE material == 'Iron ore & concentrate'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as IronOre\nFROM default.material_cost_structure\nWHERE material == 'Iron ore & concentrate'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Coal\nFROM $table\nWHERE material == 'Coal concentrate'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Coal\nFROM default.material_cost_structure\nWHERE material == 'Coal concentrate'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Auxilary\nFROM $table\nWHERE material == 'Auxilary materials'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Auxilary\nFROM default.material_cost_structure\nWHERE material == 'Auxilary materials'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as OtherMain\nFROM $table\nWHERE material == 'Other main materials'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as OtherMain\nFROM default.material_cost_structure\nWHERE material == 'Other main materials'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Fuel\nFROM $table\nWHERE material == 'Fuel'\nGROUP BY q\nORDER BY q, Fuel\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Fuel\nFROM default.material_cost_structure\nWHERE material == 'Fuel'\nGROUP BY q\nORDER BY q, Fuel",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Gas\nFROM $table\nWHERE material == 'Gas'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Gas\nFROM default.material_cost_structure\nWHERE material == 'Gas'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Power\nFROM $table\nWHERE material == 'Power'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Power\nFROM default.material_cost_structure\nWHERE material == 'Power'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    }
   ]
  },
  {
   "title": "Корреляция индекса ЖРС и железной части кеш-кост сляба",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(week, $price_lag_weeks, date))) as q,\n    avg(close) as 62PercFe\nfrom $table\nWHERE code == 'SGXIOSc1'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(week, 18, date))) as q,\n    avg(close) as 62PercFe\nfrom default.stock_prices\nWHERE code == 'SGXIOSc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * FROM (\nSELECT q, sum(perc) as IronSlab FROM (\nSELECT\n    quarter as q,\n    last_value(slab_cash_cost_structure.value)*last_value(financial_ratios.value) as perc\nFROM slab_cash_cost_structure\n       LEFT JOIN financial_ratios ON\n           financial_ratios.quarter == slab_cash_cost_structure.quarter\n        and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\nWHERE (structure == 'Pellets'\n   or structure == 'Iron ore & concentrate'\n   or structure == 'Metal scrap')\n   and indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q, structure)\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , $forecast_IronSlab))\nORDER BY q",
     "rawQuery": "select * FROM (\nSELECT q, sum(perc) as IronSlab FROM (\nSELECT\n    quarter as q,\n    last_value(slab_cash_cost_structure.value)*last_value(financial_ratios.value) as perc\nFROM slab_cash_cost_structure\n       LEFT JOIN financial_ratios ON\n           financial_ratios.quarter == slab_cash_cost_structure.quarter\n        and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\nWHERE (structure == 'Pellets'\n   or structure == 'Iron ore & concentrate'\n   or structure == 'Metal scrap')\n   and indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q, structure)\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 273))\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    }
   ]
  },
  {
   "title": "Корреляция индекса Фьючерс на коксующийся уголь и угля в стоимости кеш-кост сляба",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(week, $price_lag_weeks, date))) as q,\n    avg(close)/17.4 as \"Coking Coal CHINA\"\nfrom $table\nWHERE code == 'DJMc1'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(week, 18, date))) as q,\n    avg(close)/17.4 as \"Coking Coal CHINA\"\nfrom default.stock_prices\nWHERE code == 'DJMc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM(\nSELECT q, sum(perc) as \"Coal in Slab\" FROM (\nSELECT\n    quarter as q,\n    last_value(slab_cash_cost_structure.value)*last_value(financial_ratios.value) as perc\nFROM slab_cash_cost_structure\n       LEFT JOIN financial_ratios ON\n           financial_ratios.quarter == slab_cash_cost_structure.quarter\n        and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\nWHERE structure == 'Coal concentrate' and indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q, structure)\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 76))\nORDER BY q",
     "rawQuery": "SELECT * FROM(\nSELECT q, sum(perc) as \"Coal in Slab\" FROM (\nSELECT\n    quarter as q,\n    last_value(slab_cash_cost_structure.value)*last_value(financial_ratios.value) as perc\nFROM slab_cash_cost_structure\n       LEFT JOIN financial_ratios ON\n           financial_ratios.quarter == slab_cash_cost_structure.quarter\n        and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\nWHERE structure == 'Coal concentrate' and indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q, structure)\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 76))\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    }
   ]
  }
 ]
}