{
 "title": "MAGN Forecast",
 "time": { "from": "now-4y+4M", "to": "now+1M" },
 "templating": {
  "list": [
   { "name": "sec_code", "label": "sec_code", "query": "SELECT seccode FROM securities" },
   { "name": "price_lag_months", "query": "0,1,1.25,1.5,1.75,2" },
   { "name": "forecast_IronSlab", "query": "244" },
   { "name": "forecast_PriceAverage", "query": "916" },
   {
    "name": "forecast_Slab",
    "query": "SELECT floor(sum(perc)+$forecast_IronSlab,1) as Slab\nFROM (\n      SELECT last_value(quarter) as q,\n             last_value(slab_cash_cost_structure.value) * last_value(financial_ratios.value) as perc\n      FROM slab_cash_cost_structure\n               LEFT JOIN financial_ratios ON\n              financial_ratios.quarter == slab_cash_cost_structure.quarter\n              and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\n      WHERE (structure == 'Pellets'\n   or structure == 'Iron ore & concentrate'\n   or structure == 'Metal scrap')\n        and indicator == 'Slab Cash cost (USD/t)'\n      GROUP BY structure)\nGROUP BY q\nORDER BY q"
   },
   { "name": "forecast_sales", "query": "3320" },
   { "name": "price_lag_weeks", "query": "13,15,17,18,19" },
   { "name": "forecast_price", "query": "78" }
  ]
 },
 "panels": [
  { "title": "TRANSAQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Price History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avgWeighted(close, volume) as price\nFROM $table\nWHERE\n    date >= toDate($from) AND date <= toDate($to)\n    and sec_code == 'MAGN'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avgWeighted(close, volume) as price\nFROM default.candles\nWHERE\n    date >= toDate(1597650015) AND date <= toDate(1637134815)\n    and sec_code == 'MAGN'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "candles"
    },
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avg(close) as \"HRC FOB CHINA\"\nFROM $table\nWHERE date >= toDate($from) AND date <= toDate($to) and code == 'MHCc1'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avg(close) as \"HRC FOB CHINA\"\nFROM default.stock_prices\nWHERE date >= toDate(1597650015) AND date <= toDate(1637134815) and code == 'MHCc1'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "stock_prices"
    }
   ]
  },
  {
   "title": "Price History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select q, (max(price)*11174.33)/(sum(value)*73) as \"4Q EV/EBITDA\" \n  FROM (select p.q, p.price, t.value FROM (\n    SELECT toDate(toStartOfQuarter(date_add(day, 44 , date))) as q, avgWeighted(close, volume) as price\n      FROM candles\n      WHERE sec_code == 'MAGN' and period == 5\n      GROUP BY q) as p\n    LEFT JOIN $table as t ON p.q == t.quarter\n  WHERE t.indicator == 'EBITDA' and t.sec_code == 'MAGN'\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(quarter, 1, $dateCol))) as q, 0 as price, last_value(value) as value FROM $table WHERE sec_code == 'MAGN' GROUP BY q)\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(quarter, 2, $dateCol))) as q, 0 as price, last_value(value) as value FROM $table WHERE sec_code == 'MAGN' GROUP BY q)\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(quarter, 3, $dateCol))) as q, 0 as price, last_value(value) as value FROM $table WHERE sec_code == 'MAGN' GROUP BY q)\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , $forecast_price as price, 1358)\n  )\nGROUP BY q\nORDER by q",
     "rawQuery": "select q, (max(price)*11174.33)/(sum(value)*73) as \"4Q EV/EBITDA\" \n  FROM (select p.q, p.price, t.value FROM (\n    SELECT toDate(toStartOfQuarter(date_add(day, 44 , date))) as q, avgWeighted(close, volume) as price\n      FROM candles\n      WHERE sec_code == 'MAGN' and period == 5\n      GROUP BY q) as p\n    LEFT JOIN default.financial_highlights as t ON p.q == t.quarter\n  WHERE t.indicator == 'EBITDA' and t.sec_code == 'MAGN'\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(quarter, 1, quarter))) as q, 0 as price, last_value(value) as value FROM default.financial_highlights WHERE sec_code == 'MAGN' GROUP BY q)\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(quarter, 2, quarter))) as q, 0 as price, last_value(value) as value FROM default.financial_highlights WHERE sec_code == 'MAGN' GROUP BY q)\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(quarter, 3, quarter))) as q, 0 as price, last_value(value) as value FROM default.financial_highlights WHERE sec_code == 'MAGN' GROUP BY q)\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 69 as price, 1358)\n  )\nGROUP BY q\nORDER by q",
     "round": "0s",
     "table": "financial_highlights"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * from (select p.q, (p.price*11174.33)/((t.value*73)*4) as \"1Q EV/EBITDA\" FROM (\nSELECT\n    toDate(toStartOfQuarter(date_add(day, 44 , date))) as q,\n    avgWeighted(close, volume) as price\nFROM candles\nWHERE sec_code == 'MAGN' and period == 5\nGROUP BY q) as p\nLEFT JOIN $table as t ON p.q == t.quarter\nWHERE t.indicator == 'EBITDA' and t.sec_code == 'MAGN'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , $forecast_price*11174.33/(1358*73*4)))\nORDER by q",
     "rawQuery": "select * from (select p.q, (p.price*11174.33)/((t.value*73)*4) as \"1Q EV/EBITDA\" FROM (\nSELECT\n    toDate(toStartOfQuarter(date_add(day, 44 , date))) as q,\n    avgWeighted(close, volume) as price\nFROM candles\nWHERE sec_code == 'MAGN' and period == 5\nGROUP BY q) as p\nLEFT JOIN default.financial_highlights as t ON p.q == t.quarter\nWHERE t.indicator == 'EBITDA' and t.sec_code == 'MAGN'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 69*11174.33/(1358*73*4)))\nORDER by q",
     "round": "0s",
     "table": "financial_highlights"
    },
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * FROM (SELECT\n    toDate(toStartOfQuarter(date_add(day, 44 , date))) as q,\n    avgWeighted(close, volume) as \"Stock price\"\nFROM $table\nWHERE\n    $timeFilter\n    and sec_code == 'MAGN' and period == 5\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , $forecast_price))\nORDER BY q",
     "rawQuery": "select * FROM (SELECT\n    toDate(toStartOfQuarter(date_add(day, 44 , date))) as q,\n    avgWeighted(close, volume) as \"Stock price\"\nFROM default.candles\nWHERE\n    date >= toDateTime(1521214214) AND date <= toDateTime(1637076614)\n    and sec_code == 'MAGN' and period == 5\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 69))\nORDER BY q",
     "round": "0s",
     "table": "candles"
    }
   ]
  },
  { "title": "HIGHLIGHTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Динамика Выручки и EBITDA",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select quarter_name, CAPEX, EBITDA, Revenue from (select $dateCol as q,\n       last_value(multiIf(equals(indicator,'CAPEX'), value, NULL)) as CAPEX,\n       last_value(multiIf(equals(indicator,'EBITDA'), value, NULL)) as EBITDA,\n       last_value(multiIf(equals(indicator,'Revenue'), value, NULL)) as Revenue,\n       quarter_name\n       \nfrom $table where sec_code == 'MAGN' and $dateCol >= toDate($from) and $dateCol <= toDate($to)\ngroup by quarter_name, $dateCol\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , -250, 1291, 2918, 'Q3 2021' as quarter_name)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 6, now()))) as q , -250, 1072, 2720, 'Q4 2021' as quarter_name)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 9, now()))) as q , -250, 900, 2500, 'Q1 2022' as quarter_name)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 9, now()))) as q , -200, 850, 2200, 'Q2 2022' as quarter_name)\n)\norder by q\n",
     "rawQuery": "select quarter_name, CAPEX, EBITDA, Revenue from (select quarter as q,\n       last_value(multiIf(equals(indicator,'CAPEX'), value, NULL)) as CAPEX,\n       last_value(multiIf(equals(indicator,'EBITDA'), value, NULL)) as EBITDA,\n       last_value(multiIf(equals(indicator,'Revenue'), value, NULL)) as Revenue,\n       quarter_name\n       \nfrom default.financial_highlights where sec_code == 'MAGN' and quarter >= toDate(1523563942) and quarter <= toDate(1642018342)\ngroup by quarter_name, quarter\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , -250, 1291, 2918, 'Q3 2021' as quarter_name)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 6, now()))) as q , -250, 1072, 2720, 'Q4 2021' as quarter_name)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 9, now()))) as q , -250, 900, 2500, 'Q1 2022' as quarter_name)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 9, now()))) as q , -200, 850, 2200, 'Q2 2022' as quarter_name)\n)\norder by q",
     "round": "0s",
     "table": "financial_highlights"
    }
   ]
  },
  {
   "title": "Динамика Свободного денежного потока",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select quarter_name,\n       last_value(multiIf(equals(indicator,'Free-cash flow (FCF)'), value, NULL)) as FCF,\n       last_value(multiIf(equals(indicator,'Dividends paid'), value, NULL)) as Dividends\nfrom $table a where sec_code == 'MAGN' and $dateCol >= toDate($from) and $dateCol <= toDate($to)\ngroup by quarter_name,$dateCol\norder by $dateCol\n\n\n",
     "rawQuery": "select quarter_name,\n       last_value(multiIf(equals(indicator,'Free-cash flow (FCF)'), value, NULL)) as FCF,\n       last_value(multiIf(equals(indicator,'Dividends paid'), value, NULL)) as Dividends\nfrom default.financial_highlights a where sec_code == 'MAGN' and quarter >= toDate(1521186108) and quarter <= toDate(1637048508)\ngroup by quarter_name,quarter\norder by quarter",
     "round": "0s",
     "table": "financial_highlights"
    }
   ]
  },
  {
   "title": "Производственные показатели консолидированные,  тыс. тон",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    production as p,\n    last_value(value) as v\nFROM $table\nWHERE sec_code == 'MAGN' and $dateCol >= toDate($from) and $dateCol <= toDate($to) and has(array('Iron ore production', 'Crude steel production', 'Coking coal concentrate production', 'Pig iron production'), p) == 1\nGROUP BY q, p\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    production as p,\n    last_value(value) as v\nFROM default.productions\nWHERE sec_code == 'MAGN' and quarter >= toDate(1526137605) and quarter <= toDate(1634051205) and has(array('Iron ore production', 'Crude steel production', 'Coking coal concentrate production', 'Pig iron production'), p) == 1\nGROUP BY q, p\nORDER BY q",
     "round": "0s",
     "table": "productions"
    }
   ]
  },
  {
   "title": "Производственные показатели,  тыс. тон",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select q, sum(v) as \"Premium products\" FROM (\nSELECT\n    $dateCol as q,\n    production as p,\n    last_value(value) as v,\n    division\nFROM $table\nWHERE sec_code == 'MAGN' and $dateCol >= toDate($from) and $dateCol <= toDate($to) and has(array('Premium products, of which', 'Premium products'), p) == 1\nGROUP BY q, p, division)\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "select q, sum(v) as \"Premium products\" FROM (\nSELECT\n    quarter as q,\n    production as p,\n    last_value(value) as v,\n    division\nFROM default.productions\nWHERE sec_code == 'MAGN' and quarter >= toDate(1526139180) and quarter <= toDate(1634052780) and has(array('Premium products, of which', 'Premium products'), p) == 1\nGROUP BY q, p, division)\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "productions"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select q, p, sum(v) FROM (\nSELECT\n    $dateCol as q,\n    production as p,\n    last_value(value) as v,\n    division\nFROM $table\nWHERE sec_code == 'MAGN' and $dateCol >= toDate($from) and $dateCol <= toDate($to) and has(array('Pig iron', 'Crude steel', 'Finished products, incl.'), p) == 1\nGROUP BY q, p, division)\nGROUP BY q, p\nORDER BY q\n",
     "rawQuery": "select q, p, sum(v) FROM (\nSELECT\n    quarter as q,\n    production as p,\n    last_value(value) as v,\n    division\nFROM default.productions\nWHERE sec_code == 'MAGN' and quarter >= toDate(1526139180) and quarter <= toDate(1634052780) and has(array('Pig iron', 'Crude steel', 'Finished products, incl.'), p) == 1\nGROUP BY q, p, division)\nGROUP BY q, p\nORDER BY q",
     "round": "0s",
     "table": "productions"
    }
   ]
  },
  {
   "title": "Консолидированные продажи по видам продукции,  тыс. тон",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select t, avg(LoadingRZD*1000) as \"Loading yuzd avg\" FROM (SELECT $dateCol as t, last_value(value) as LoadingRZD FROM $table WHERE name == 'yuzd' GROUP BY t\nUNION ALL (SELECT toDate(toStartOfMonth(date_add(month, -1, $dateCol))) as t, last_value(value) as LoadingRZD FROM $table WHERE name == 'yuzd' GROUP BY t))\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "select t, avg(LoadingRZD*1000) as \"Loading yuzd avg\" FROM (SELECT month as t, last_value(value) as LoadingRZD FROM default.loading_rzd WHERE name == 'yuzd' GROUP BY t\nUNION ALL (SELECT toDate(toStartOfMonth(date_add(month, -1, month))) as t, last_value(value) as LoadingRZD FROM default.loading_rzd WHERE name == 'yuzd' GROUP BY t))\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "loading_rzd"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select q,p,last_value(v) FROM (SELECT\n    $dateCol as q,\n    product as p,\n    last_value(value) as v\nFROM $table\nWHERE has(array('Premium products', 'Flat hot-rolled products', 'Long products'), p) == 1 and sec_code == 'MAGN'\nGROUP BY q, p\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 'Long products' as p, 270 as value)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 'Premium products' as p, 1300 as value)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 'Flat hot-rolled products' as p, 1658 as value)\n)\nGROUP BY q,p\nORDER BY q",
     "rawQuery": "select q,p,last_value(v) FROM (SELECT\n    quarter as q,\n    product as p,\n    last_value(value) as v\nFROM default.consolidated_sales_for_products\nWHERE has(array('Premium products', 'Flat hot-rolled products', 'Long products'), p) == 1 and sec_code == 'MAGN'\nGROUP BY q, p\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 'Long products' as p, 270 as value)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 'Premium products' as p, 1300 as value)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 'Flat hot-rolled products' as p, 1658 as value)\n)\nGROUP BY q,p\nORDER BY q",
     "round": "0s",
     "table": "consolidated_sales_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(inv.value)*1000/last_value(prices.price)/4 as \"Inventories in HRC\"\nFROM $table as inv\nLEFT JOIN prices_for_products as prices ON prices.quarter == inv.quarter\nWHERE inv.indicator == 'Inventories' and prices.product == 'Flat hot-rolled products' and inv.sec_code == 'MAGN'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(inv.value)*1000/last_value(prices.price)/4 as \"Inventories in HRC\"\nFROM default.financial_ratios as inv\nLEFT JOIN prices_for_products as prices ON prices.quarter == inv.quarter\nWHERE inv.indicator == 'Inventories' and prices.product == 'Flat hot-rolled products' and inv.sec_code == 'MAGN'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "financial_ratios"
    },
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select t, avg(LoadingRZD*1000) as \"Loading chelzd avg\" FROM (SELECT $dateCol as t, last_value(value) as LoadingRZD FROM $table WHERE name == 'chel' GROUP BY t\nUNION ALL (SELECT toDate(toStartOfMonth(date_add(month, -1, $dateCol))) as t, last_value(value) as LoadingRZD FROM $table WHERE name == 'chel' GROUP BY t))\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "select t, avg(LoadingRZD*1000) as \"Loading chelzd avg\" FROM (SELECT month as t, last_value(value) as LoadingRZD FROM default.loading_rzd WHERE name == 'chel' GROUP BY t\nUNION ALL (SELECT toDate(toStartOfMonth(date_add(month, -1, month))) as t, last_value(value) as LoadingRZD FROM default.loading_rzd WHERE name == 'chel' GROUP BY t))\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "loading_rzd"
    }
   ]
  },
  {
   "title": "Разница между консолидированными продажами и производством сырой стали  ,  тыс. тон",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    sales.quarter as q,\n    last_value(prod_mmk.value) - last_value(sales.value)*1.103 as \"crude steel - sales products\"\nFROM $table as sales\nLEFT JOIN productions as prod_mmk ON sales.quarter == prod_mmk.quarter and sales.sec_code == prod_mmk.sec_code\nWHERE sales.product == 'Sales of finished products' and sales.sec_code == 'MAGN' \nand prod_mmk.production = 'Crude steel' and prod_mmk.division = 'PJSC MMK PRODUCTION' \nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    sales.quarter as q,\n    last_value(prod_mmk.value) - last_value(sales.value)*1.103 as \"crude steel - sales products\"\nFROM default.consolidated_sales_for_products as sales\nLEFT JOIN productions as prod_mmk ON sales.quarter == prod_mmk.quarter and sales.sec_code == prod_mmk.sec_code\nWHERE sales.product == 'Sales of finished products' and sales.sec_code == 'MAGN' \nand prod_mmk.production = 'Crude steel' and prod_mmk.division = 'PJSC MMK PRODUCTION' \nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "consolidated_sales_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    sales.quarter as q,\n    last_value(prod_mmk.value) + last_value(prod_tur.value) - last_value(sales.value) + last_value(sales_int.value) as \"not sales finished products\"\nFROM $table as sales\nLEFT JOIN productions as prod_mmk ON sales.quarter == prod_mmk.quarter and sales.sec_code == prod_mmk.sec_code\nLEFT JOIN productions as prod_tur ON sales.quarter == prod_tur.quarter and sales.sec_code == prod_tur.sec_code and prod_tur.production == prod_mmk.production\nLEFT JOIN operational_highlights as sales_int ON sales.quarter == sales_int.quarter and sales.sec_code == sales_int.sec_code\nWHERE sales.product == 'Sales of finished products' and sales.sec_code == 'MAGN' \nand prod_mmk.production = 'Finished products, incl.' and prod_mmk.division = 'PJSC MMK PRODUCTION'and sales_int.product = 'Intersegment sales'\nand prod_tur.division = 'MMK METALURJI (STEEL TURKEY) PRODUCTION'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    sales.quarter as q,\n    last_value(prod_mmk.value) + last_value(prod_tur.value) - last_value(sales.value) + last_value(sales_int.value) as \"not sales finished products\"\nFROM default.consolidated_sales_for_products as sales\nLEFT JOIN productions as prod_mmk ON sales.quarter == prod_mmk.quarter and sales.sec_code == prod_mmk.sec_code\nLEFT JOIN productions as prod_tur ON sales.quarter == prod_tur.quarter and sales.sec_code == prod_tur.sec_code and prod_tur.production == prod_mmk.production\nLEFT JOIN operational_highlights as sales_int ON sales.quarter == sales_int.quarter and sales.sec_code == sales_int.sec_code\nWHERE sales.product == 'Sales of finished products' and sales.sec_code == 'MAGN' \nand prod_mmk.production = 'Finished products, incl.' and prod_mmk.division = 'PJSC MMK PRODUCTION'and sales_int.product = 'Intersegment sales'\nand prod_tur.division = 'MMK METALURJI (STEEL TURKEY) PRODUCTION'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "consolidated_sales_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(inv.value)*1000/last_value(prices.price)/4 as \"Inventories in HRC\"\nFROM $table as inv\nLEFT JOIN prices_for_products as prices ON prices.quarter == inv.quarter\nWHERE inv.indicator == 'Inventories' and prices.product == 'Flat hot-rolled products' and inv.sec_code == 'MAGN'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(inv.value)*1000/last_value(prices.price)/4 as \"Inventories in HRC\"\nFROM default.financial_ratios as inv\nLEFT JOIN prices_for_products as prices ON prices.quarter == inv.quarter\nWHERE inv.indicator == 'Inventories' and prices.product == 'Flat hot-rolled products' and inv.sec_code == 'MAGN'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "financial_ratios"
    }
   ]
  },
  {
   "title": "EBITDA/т и цена реализации металлопродукции USD/т",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (SELECT\n    $dateCol as q,\n    last_value(value) as \"EBITDA per tonne\"\nFROM $table\nWHERE indicator == 'EBITDA per tonne* (USD/t)'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 381.4))\nORDER BY q",
     "rawQuery": "SELECT * FROM (SELECT\n    quarter as q,\n    last_value(value) as \"EBITDA per tonne\"\nFROM default.financial_ratios\nWHERE indicator == 'EBITDA per tonne* (USD/t)'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 381.4))\nORDER BY q",
     "round": "0s",
     "table": "financial_ratios"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(value) as \"Slab Cash cost\"\nFROM $table\nWHERE indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q\nORDER BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , $forecast_Slab)",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as \"Slab Cash cost\"\nFROM default.financial_ratios\nWHERE indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q\nORDER BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 372.6)",
     "round": "0s",
     "table": "financial_ratios"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (SELECT\n    $dateCol as q,\n    last_value(price) as ConsolidateWeightedAverage\nFROM $table\nWHERE product == 'Sales of finished products'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , $forecast_PriceAverage))\nORDER BY q\n",
     "rawQuery": "SELECT * FROM (SELECT\n    quarter as q,\n    last_value(price) as ConsolidateWeightedAverage\nFROM default.consolidated_prices_for_products\nWHERE product == 'Sales of finished products'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 965))\nORDER BY q",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (\nSELECT p.quarter, last_value(p.price) - last_value(e.value) - last_value(s.value) as \"Other production\"\nFROM consolidated_prices_for_products as p\nLEFT JOIN financial_ratios as e on e.quarter == p.quarter and e.sec_code == p.sec_code\nLEFT JOIN financial_ratios as s on s.quarter == p.quarter and s.sec_code == p.sec_code\nWHERE p.sec_code == 'MAGN' and p.product == 'Sales of finished products' and e.indicator == 'EBITDA per tonne* (USD/t)' and s.indicator == 'Slab Cash cost (USD/t)'\nGROUP BY p.quarter\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 211))\nORDER BY p.quarter",
     "rawQuery": "SELECT * FROM (\nSELECT p.quarter, last_value(p.price) - last_value(e.value) - last_value(s.value) as \"Other production\"\nFROM consolidated_prices_for_products as p\nLEFT JOIN financial_ratios as e on e.quarter == p.quarter and e.sec_code == p.sec_code\nLEFT JOIN financial_ratios as s on s.quarter == p.quarter and s.sec_code == p.sec_code\nWHERE p.sec_code == 'MAGN' and p.product == 'Sales of finished products' and e.indicator == 'EBITDA per tonne* (USD/t)' and s.indicator == 'Slab Cash cost (USD/t)'\nGROUP BY p.quarter\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 211))\nORDER BY p.quarter",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    }
   ]
  },
  {
   "title": "Выручка расчетная и EBITDA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * FROM (\n    SELECT\n    $dateCol as q,\n    last_value(prices.price)*last_value(sales.value)/1000 as calculatedRevenue\nFROM $table as prices\nLEFT JOIN consolidated_sales_for_products as sales on (prices.sec_code == sales.sec_code and prices.quarter == sales.quarter)\nWHERE prices.product == 'Sales of finished products, including:' and sales.product == 'Sales of finished products, including:'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , $forecast_PriceAverage*$forecast_sales/1000 as Revenue))\nORDER BY q\n\n",
     "rawQuery": "select * FROM (\n    SELECT\n    quarter as q,\n    last_value(prices.price)*last_value(sales.value)/1000 as calculatedRevenue\nFROM default.consolidated_prices_for_products as prices\nLEFT JOIN consolidated_sales_for_products as sales on (prices.sec_code == sales.sec_code and prices.quarter == sales.quarter)\nWHERE prices.product == 'Sales of finished products, including:' and sales.product == 'Sales of finished products, including:'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 944*3320/1000 as Revenue))\nORDER BY q",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * FROM (SELECT\n    $dateCol as q,\n    last_value(value) as EBITDA\nFROM $table\nWHERE indicator == 'EBITDA' and sec_code == 'MAGN'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 444*$forecast_sales/1000 as EBITDA))\nORDER BY q\n",
     "rawQuery": "select * FROM (SELECT\n    quarter as q,\n    last_value(value) as EBITDA\nFROM default.financial_highlights\nWHERE indicator == 'EBITDA' and sec_code == 'MAGN'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 444*3320/1000 as EBITDA))\nORDER BY q",
     "round": "0s",
     "table": "financial_highlights"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * FROM (SELECT\n    $dateCol as q,\n    last_value(value) as Revenue\nFROM $table\nWHERE indicator == 'Revenue' and sec_code == 'MAGN'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , $forecast_PriceAverage*$forecast_sales*1.04/1000 as Revenue))\nORDER BY q\n",
     "rawQuery": "select * FROM (SELECT\n    quarter as q,\n    last_value(value) as Revenue\nFROM default.financial_highlights\nWHERE indicator == 'Revenue' and sec_code == 'MAGN'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q , 944*3320*1.04/1000 as Revenue))\nORDER BY q",
     "round": "0s",
     "table": "financial_highlights"
    }
   ]
  },
  { "title": "Production & Sales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Цены за тонну продукции",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as FlatHotRolled\nFROM $table\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as FlatHotRolled\nFROM default.prices_for_products\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as ConsolidateWeightedAverage\nFROM $table\nWHERE product == 'Sales of finished products'\nGROUP BY q\nORDER BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , $forecast_PriceAverage)",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as ConsolidateWeightedAverage\nFROM default.consolidated_prices_for_products\nWHERE product == 'Sales of finished products'\nGROUP BY q\nORDER BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 980)",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as ExportAverage\nFROM $table\nWHERE product == 'Export'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as ExportAverage\nFROM default.prices_for_products\nWHERE product == 'Export'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "prices_for_products"
    },
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(toStartOfQuarter(date_add(month, $price_lag_months, date))) as q,\n    avg(close) as \"HRC FOB CHINA with month lag\"\nFROM $table\n\nWHERE code == 'MHCc1'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    toDate(toStartOfQuarter(date_add(month, 4, date))) as q,\n    avg(close) as \"HRC FOB CHINA with month lag\"\nFROM default.stock_prices\n\nWHERE code == 'MHCc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(toStartOfQuarter(date_add(month, 3, date))) as q,\n    avg(close) as \"HRC FOB CHINA avg\"\nFROM $table\n\nWHERE code == 'MHCc1'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    toDate(toStartOfQuarter(date_add(month, 3, date))) as q,\n    avg(close) as \"HRC FOB CHINA avg\"\nFROM default.stock_prices\n\nWHERE code == 'MHCc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avg(close) as \"HRC FOB CHINA\"\nFROM $table\nWHERE date >= toDate($from) AND date <= toDate($to) and code == 'MHCc1' \nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avg(close) as \"HRC FOB CHINA\"\nFROM default.stock_prices\nWHERE date >= toDate(1552750701) AND date <= toDate(1634398701) and code == 'MHCc1' \nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "stock_prices"
    }
   ]
  },
  {
   "title": "Консолидированные продажи, ton",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    product,\n    last_value(value)\nFROM $table\nWHERE sec_code == 'MAGN' and has(array('Premium products','Long products', 'Flat hot-rolled products'), product) == 1\nGROUP BY q, product\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    product,\n    last_value(value)\nFROM default.consolidated_sales_for_products\nWHERE sec_code == 'MAGN' and has(array('Premium products','Long products', 'Flat hot-rolled products'), product) == 1\nGROUP BY q, product\nORDER BY q",
     "round": "0s",
     "table": "consolidated_sales_for_products"
    }
   ]
  },
  {
   "title": "Консолидированные цены продаж",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    product,\n    last_value(price)\nFROM $table\nWHERE sec_code == 'MAGN' and has(array('HVA products, including:','Long products', 'Flat hot-rolled products'), product) == 1\nGROUP BY q, product\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    product,\n    last_value(price)\nFROM default.consolidated_prices_for_products\nWHERE sec_code == 'MAGN' and has(array('HVA products, including:','Long products', 'Flat hot-rolled products'), product) == 1\nGROUP BY q, product\nORDER BY q",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as \"MMK HRC FOB CHINA\"\nFROM $table\nWHERE product == 'HRC FOB CHINA'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as \"MMK HRC FOB CHINA\"\nFROM default.fob_prices\nWHERE product == 'HRC FOB CHINA'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "fob_prices"
    }
   ]
  },
  {
   "title": "Динамика цен на г/к прокат в дол. США",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (\nSELECT\n    $dateCol as q,\n    last_value(price) as \"HRC MMK price\"\nFROM $table\nWHERE product == 'Flat hot-rolled products' and sec_code == 'MAGN'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , $forecast_PriceAverage/1.12))\nORDER BY q",
     "rawQuery": "SELECT * FROM (\nSELECT\n    quarter as q,\n    last_value(price) as \"HRC MMK price\"\nFROM default.prices_for_products\nWHERE product == 'Flat hot-rolled products' and sec_code == 'MAGN'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 965/1.12))\nORDER BY q",
     "round": "0s",
     "table": "prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(toStartOfQuarter(date_add(week, $price_lag_weeks, date))) as q,\n    avg(close) as \"HRC FOB CHINA\"\nFROM $table\nWHERE code == 'MHCc1'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    toDate(toStartOfQuarter(date_add(week, 18, date))) as q,\n    avg(close) as \"HRC FOB CHINA\"\nFROM default.stock_prices\nWHERE code == 'MHCc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (\nSELECT\n    $dateCol as q,\n    last_value(price) as \"Average cons\"\nFROM $table\nWHERE product == 'Sales of finished products'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , $forecast_PriceAverage))\nORDER BY q\n",
     "rawQuery": "SELECT * FROM (\nSELECT\n    quarter as q,\n    last_value(price) as \"Average cons\"\nFROM default.consolidated_prices_for_products\nWHERE product == 'Sales of finished products'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 965))\nORDER BY q",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as \"MMK HRC FOB CHINA\"\nFROM $table\nWHERE product == 'HRC FOB CHINA'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as \"MMK HRC FOB CHINA\"\nFROM default.fob_prices\nWHERE product == 'HRC FOB CHINA'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "fob_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as \"MMK HRC FOB BS\"\nFROM $table\nWHERE product == 'HRC FOB Black sea'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as \"MMK HRC FOB BS\"\nFROM default.fob_prices\nWHERE product == 'HRC FOB Black sea'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "fob_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (\nSELECT\n    $dateCol as q,\n    last_value(price) as \"HRC cons\"\nFROM $table\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , $forecast_PriceAverage/1.12))\nORDER BY q\n",
     "rawQuery": "SELECT * FROM (\nSELECT\n    quarter as q,\n    last_value(price) as \"HRC cons\"\nFROM default.consolidated_prices_for_products\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 965/1.12))\nORDER BY q",
     "round": "0s",
     "table": "consolidated_prices_for_products"
    }
   ]
  },
  { "title": "COS breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Структура затрат",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Other\nFROM $table\n\nWHERE structure == 'Other production costs'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Other\nFROM default.cost_of_sales_structure\n\nWHERE structure == 'Other production costs'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Services\nFROM $table\n\nWHERE structure == 'Services received'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Services\nFROM default.cost_of_sales_structure\n\nWHERE structure == 'Services received'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Depreciation\nFROM $table\n\nWHERE structure == 'Depreciation'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Depreciation\nFROM default.cost_of_sales_structure\n\nWHERE structure == 'Depreciation'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Labour\nFROM $table\n\nWHERE structure == 'Labour costs'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Labour\nFROM default.cost_of_sales_structure\n\nWHERE structure == 'Labour costs'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Material\nFROM $table\n\nWHERE structure == 'Material costs'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Material\nFROM default.cost_of_sales_structure\n\nWHERE structure == 'Material costs'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    }
   ]
  },
  {
   "title": "Затраты на материалы, USD mln",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Scrap\nFROM $table\nWHERE material == 'Metal scrap'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Scrap\nFROM default.material_cost_structure\nWHERE material == 'Metal scrap'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Pellets\nFROM $table\nWHERE material == 'Pellets'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Pellets\nFROM default.material_cost_structure\nWHERE material == 'Pellets'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as IronOre\nFROM $table\nWHERE material == 'Iron ore & concentrate'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as IronOre\nFROM default.material_cost_structure\nWHERE material == 'Iron ore & concentrate'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Coal\nFROM $table\nWHERE material == 'Coal concentrate'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Coal\nFROM default.material_cost_structure\nWHERE material == 'Coal concentrate'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Auxilary\nFROM $table\nWHERE material == 'Auxilary materials'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Auxilary\nFROM default.material_cost_structure\nWHERE material == 'Auxilary materials'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as OtherMain\nFROM $table\nWHERE material == 'Other main materials'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as OtherMain\nFROM default.material_cost_structure\nWHERE material == 'Other main materials'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Fuel\nFROM $table\nWHERE material == 'Fuel'\nGROUP BY q\nORDER BY q, Fuel\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Fuel\nFROM default.material_cost_structure\nWHERE material == 'Fuel'\nGROUP BY q\nORDER BY q, Fuel",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Gas\nFROM $table\nWHERE material == 'Gas'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Gas\nFROM default.material_cost_structure\nWHERE material == 'Gas'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value) as Power\nFROM $table\nWHERE material == 'Power'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as Power\nFROM default.material_cost_structure\nWHERE material == 'Power'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    }
   ]
  },
  {
   "title": "Корреляция индекса ЖРС и железной части кеш-кост сляба",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(week, $price_lag_weeks, date))) as q,\n    avg(close) as 62PercFe\nfrom $table\nWHERE code == 'SGXIOSc1'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(week, 18, date))) as q,\n    avg(close) as 62PercFe\nfrom default.stock_prices\nWHERE code == 'SGXIOSc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * FROM (\nSELECT q, sum(perc) as IronSlab FROM (\nSELECT\n    quarter as q,\n    last_value(slab_cash_cost_structure.value)*last_value(financial_ratios.value) as perc\nFROM slab_cash_cost_structure\n       LEFT JOIN financial_ratios ON\n           financial_ratios.quarter == slab_cash_cost_structure.quarter\n        and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\nWHERE (structure == 'Pellets'\n   or structure == 'Iron ore & concentrate'\n   or structure == 'Metal scrap')\n   and indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q, structure)\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , $forecast_IronSlab))\nORDER BY q",
     "rawQuery": "select * FROM (\nSELECT q, sum(perc) as IronSlab FROM (\nSELECT\n    quarter as q,\n    last_value(slab_cash_cost_structure.value)*last_value(financial_ratios.value) as perc\nFROM slab_cash_cost_structure\n       LEFT JOIN financial_ratios ON\n           financial_ratios.quarter == slab_cash_cost_structure.quarter\n        and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\nWHERE (structure == 'Pellets'\n   or structure == 'Iron ore & concentrate'\n   or structure == 'Metal scrap')\n   and indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q, structure)\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 152))\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    }
   ]
  },
  {
   "title": "Корреляция индекса Фьючерс на коксующийся уголь и угля в стоимости кеш-кост сляба",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(week, $price_lag_weeks, date))) as q,\n    avg(close)/17.4 as \"Coking Coal CHINA\"\nfrom $table\nWHERE code == 'DJMc1'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(week, 18, date))) as q,\n    avg(close)/17.4 as \"Coking Coal CHINA\"\nfrom default.stock_prices\nWHERE code == 'DJMc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM(\nSELECT q, sum(perc) as \"Coal in Slab\" FROM (\nSELECT\n    quarter as q,\n    last_value(slab_cash_cost_structure.value)*last_value(financial_ratios.value) as perc\nFROM slab_cash_cost_structure\n       LEFT JOIN financial_ratios ON\n           financial_ratios.quarter == slab_cash_cost_structure.quarter\n        and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\nWHERE structure == 'Coal concentrate' and indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q, structure)\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 138))\nORDER BY q",
     "rawQuery": "SELECT * FROM(\nSELECT q, sum(perc) as \"Coal in Slab\" FROM (\nSELECT\n    quarter as q,\n    last_value(slab_cash_cost_structure.value)*last_value(financial_ratios.value) as perc\nFROM slab_cash_cost_structure\n       LEFT JOIN financial_ratios ON\n           financial_ratios.quarter == slab_cash_cost_structure.quarter\n        and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\nWHERE structure == 'Coal concentrate' and indicator == 'Slab Cash cost (USD/t)'\nGROUP BY q, structure)\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 138))\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    }
   ]
  },
  {
   "title": "Экспорт  России",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    name,\n    last_value(quantity)\nFROM $table\nWHERE code == '72 (кроме 7201-7204)' or code=='7208-7212' \nGROUP BY q,name\nORDER BY q\n",
     "rawQuery": "SELECT\n    month as q,\n    name,\n    last_value(quantity)\nFROM default.export_goods\nWHERE code == '72 (кроме 7201-7204)' or code=='7208-7212' \nGROUP BY q,name\nORDER BY q",
     "round": "0s",
     "table": "export_goods"
    }
   ]
  },
  {
   "title": "Экспорт Челябинская область, млн. долл. США",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(if(runningDifference(export)>0,runningDifference(export),export)) as Export,\n    last_value(if(runningDifference(cis)>0,runningDifference(cis), cis)) as \"CIS\"\nFROM $table\n\nwhere name = 'ЧЕЛЯБИНСКАЯ ОБЛАСТЬ'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    month as q,\n    last_value(if(runningDifference(export)>0,runningDifference(export),export)) as Export,\n    last_value(if(runningDifference(cis)>0,runningDifference(cis), cis)) as \"CIS\"\nFROM default.export_regions\n\nwhere name = 'ЧЕЛЯБИНСКАЯ ОБЛАСТЬ'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "export_regions"
    }
   ]
  }
 ]
}