{
 "title": "MOEX",
 "time": { "from": "now-5y", "to": "now+4M" },
 "panels": [
  {
   "title": "Net profit и Stock Price",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avgWeighted(close*1000, volume)/1000 as \"Stock price\"\nFROM $table\nWHERE\n    date >= toDate($from) AND date <= toDate($to)\n    and sec_code == 'MOEX' and period == '5' \nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avgWeighted(close*1000, volume)/1000 as \"Stock price\"\nFROM default.candles\nWHERE\n    date >= toDate(1364390864) AND date <= toDate(1651069664)\n    and sec_code == 'MOEX' and period == '5' \nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "candles"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT date_add(day, 30 , quarter) as q, last_value(value), name\nFROM $table\nWHERE q >= toDateTime($from) and q < toDateTime($to) \nand code == 'MOEX' and content == '3. P&L - reporting periods'\nand name in ('Net profit')\nGROUP BY q, name\nORDER BY q, sum(value)\n",
     "rawQuery": "SELECT date_add(day, 30 , quarter) as q, last_value(value), name\nFROM default.databook\nWHERE q >= toDateTime(1364390293) and q < toDateTime(1640614693) \nand code == 'MOEX' and content == '3. P&L - reporting periods'\nand name in ('Net profit')\nGROUP BY q, name\nORDER BY q, sum(value)",
     "round": "0s",
     "table": "databook"
    }
   ]
  },
  {
   "title": "Dividend и Stock Price",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avgWeighted(close*1000, volume)/1000 as \"Stock price\"\nFROM $table\nWHERE\n    date >= toDate($from) AND date <= toDate($to)\n    and sec_code == 'MOEX' and period == '5' \nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avgWeighted(close*1000, volume)/1000 as \"Stock price\"\nFROM default.candles\nWHERE\n    date >= toDate(1364390883) AND date <= toDate(1651069683)\n    and sec_code == 'MOEX' and period == '5' \nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "candles"
    },
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT date_pub as t, value as dividend\nFROM $table\nWHERE t >= toDateTime($from) and t < toDateTime($to) \nORDER BY t\n",
     "rawQuery": "SELECT date_pub as t, value as dividend\nFROM default.dividend\nWHERE t >= toDateTime(1364390883) and t < toDateTime(1651069683) \nORDER BY t",
     "round": "0s",
     "table": "dividend"
    }
   ]
  },
  { "title": "Reporting periods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Net profit",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT quarter as q, last_value(value), name\nFROM $table\nWHERE q >= toDateTime($from) and q < toDateTime($to) \nand code == 'MOEX' and content == '3. P&L - reporting periods'\nand name in ('Net profit')\nGROUP BY q, name\nORDER BY q, sum(value)\n",
     "rawQuery": "SELECT quarter as q, last_value(value), name\nFROM default.databook\nWHERE q >= toDateTime(1545917379) and q < toDateTime(1640611779) \nand code == 'MOEX' and content == '3. P&L - reporting periods'\nand name in ('Net profit')\nGROUP BY q, name\nORDER BY q, sum(value)",
     "round": "0s",
     "table": "databook"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT quarter as q, (last_value(value)-last_value(neighbor(value, -1)))/last_value(neighbor(value, -1)) as \"Net growth\"\nFROM $table\nWHERE q >= toDateTime($from) and q < toDateTime($to) and code == 'MOEX' and content == '3. P&L - reporting periods'\nand name = 'Net profit'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT quarter as q, (last_value(value)-last_value(neighbor(value, -1)))/last_value(neighbor(value, -1)) as \"Net growth\"\nFROM default.databook\nWHERE q >= toDateTime(1545917379) and q < toDateTime(1640611779) and code == 'MOEX' and content == '3. P&L - reporting periods'\nand name = 'Net profit'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "databook"
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT quarter as q, last_value(value)*-1, name\nFROM $table\nWHERE q >= toDateTime($from) and q < toDateTime($to) \nand code == 'MOEX' and content == '3. P&L - reporting periods'\nand name in ('General and administrative expenses', 'Personnel expenses', 'Other operating expenses', 'Income tax expense')\nGROUP BY q, name\nORDER BY q, sum(value)\n",
     "rawQuery": "SELECT quarter as q, last_value(value)*-1, name\nFROM default.databook\nWHERE q >= toDateTime(1482694527) and q < toDateTime(1640460927) \nand code == 'MOEX' and content == '3. P&L - reporting periods'\nand name in ('General and administrative expenses', 'Personnel expenses', 'Other operating expenses', 'Income tax expense')\nGROUP BY q, name\nORDER BY q, sum(value)",
     "round": "0s",
     "table": "databook"
    }
   ]
  },
  {
   "title": "Fee and commission income",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT quarter as q, last_value(value), name\nFROM $table\nWHERE q >= toDateTime($from) and q < toDateTime($to) \nand code == 'MOEX' and content == '3. P&L - reporting periods'\nand name in ('Money market', 'Depository and settlement services', \n'Securities market', 'Foreign exchange', 'Derivatives', 'Information services', \n'Sale of software and technical services','Other')\nGROUP BY q, name\nORDER BY q, sum(value)\n",
     "rawQuery": "SELECT quarter as q, last_value(value), name\nFROM default.databook\nWHERE q >= toDateTime(1482691423) and q < toDateTime(1640457823) \nand code == 'MOEX' and content == '3. P&L - reporting periods'\nand name in ('Money market', 'Depository and settlement services', \n'Securities market', 'Foreign exchange', 'Derivatives', 'Information services', \n'Sale of software and technical services','Other')\nGROUP BY q, name\nORDER BY q, sum(value)",
     "round": "0s",
     "table": "databook"
    }
   ]
  },
  {
   "title": "Operating income",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT quarter as q, last_value(value), name\nFROM $table\nWHERE q >= toDateTime($from) and q < toDateTime($to) \nand code == 'MOEX' and content == '3. P&L - reporting periods'\nand name in ('Interest and other finance income', 'Fee and commission income', 'Interest expense', 'Operating income', 'Foreign exchange gains less losses')\nGROUP BY q, name\nORDER BY q, sum(value)\n",
     "rawQuery": "SELECT quarter as q, last_value(value), name\nFROM default.databook\nWHERE q >= toDateTime(1482691446) and q < toDateTime(1640457846) \nand code == 'MOEX' and content == '3. P&L - reporting periods'\nand name in ('Interest and other finance income', 'Fee and commission income', 'Interest expense', 'Operating income', 'Foreign exchange gains less losses')\nGROUP BY q, name\nORDER BY q, sum(value)",
     "round": "0s",
     "table": "databook"
    }
   ]
  }
 ]
}