{
 "title": "HLMK Forecast",
 "time": { "from": "now-3y", "to": "now" },
 "templating": {
  "list": [
   { "name": "sec_code", "label": "sec_code", "query": "SELECT seccode FROM securities" },
   { "name": "price_lag_months", "query": "0,1,1.25,1.5,1.75,2" },
   { "name": "forecast_IronSlab", "query": "244" },
   { "name": "forecast_PriceAverage", "query": "825" },
   {
    "name": "forecast_Slab",
    "query": "SELECT floor(sum(perc)+$forecast_IronSlab,1) as Slab\nFROM (\n      SELECT last_value(quarter) as q,\n             last_value(slab_cash_cost_structure.value) * last_value(financial_ratios.value) as perc\n      FROM slab_cash_cost_structure\n               LEFT JOIN financial_ratios ON\n              financial_ratios.quarter == slab_cash_cost_structure.quarter\n              and financial_ratios.sec_code == slab_cash_cost_structure.sec_code\n      WHERE (structure == 'Pellets'\n   or structure == 'Iron ore & concentrate'\n   or structure == 'Metal scrap')\n        and indicator == 'Slab Cash cost (USD/t)'\n      GROUP BY structure)\nGROUP BY q\nORDER BY q"
   },
   { "name": "forecast_price", "query": "300" },
   { "name": "shares", "query": "5993.23" }
  ]
 },
 "panels": [
  { "title": "Операционные результаты", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Производство стали, млн т",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(value),\n    name\nFROM $table\nWHERE q >= toDate($from) and q <= toDate($to) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name like 'Производство%'\nand category == 'Группа НЛМК'\nGROUP BY q, name\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value),\n    name\nFROM default.operational_databook\nWHERE q >= toDate(1485081599) and q <= toDate(1642847999) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name like 'Производство%'\nand category == 'Группа НЛМК'\nGROUP BY q, name\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(value) as \"Загрузка\"\nFROM $table\nWHERE q >= toDate($from) and q <= toDate($to) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Загрузка производственных мощностей (c NBH)'\nand category == 'Группа НЛМК'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as \"Загрузка\"\nFROM default.operational_databook\nWHERE q >= toDate(1485081599) and q <= toDate(1642847999) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Загрузка производственных мощностей (c NBH)'\nand category == 'Группа НЛМК'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    }
   ]
  },
  {
   "title": "Производство, кв/кв",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    (last_value(value)/neighbor(last_value(value), -1))-1\nFROM $table\nWHERE q >= toDate($from) and q <= toDate($to) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Производство стали (c NBH)'\nand category == 'Группа НЛМК'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    (last_value(value)/neighbor(last_value(value), -1))-1\nFROM default.operational_databook\nWHERE q >= toDate(1421922533) and q <= toDate(1642847333) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Производство стали (c NBH)'\nand category == 'Группа НЛМК'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    }
   ]
  },
  {
   "title": "Консолидированные продажи, млн т",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(value) as \"Итого\"\nFROM $table\nWHERE q >= toDate($from) and q <= toDate($to) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Итого консолидированные продажи'\nand category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as \"Итого\"\nFROM default.operational_databook\nWHERE q >= toDate(1485085070) and q <= toDate(1642851470) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Итого консолидированные продажи'\nand category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(value) as \"слябы дочкам\"\nFROM $table\nWHERE q >= toDate($from) and q <= toDate($to) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Для информации: продажи слябов на зарубежные дочерние и зависимые компании'\nand category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as \"слябы дочкам\"\nFROM default.operational_databook\nWHERE q >= toDate(1485085070) and q <= toDate(1642851470) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Для информации: продажи слябов на зарубежные дочерние и зависимые компании'\nand category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(value) as \"локальные рынки\"\nFROM $table\nWHERE q >= toDate($from) and q <= toDate($to) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Продажи на локальных рынках Группы 3'\nand category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as \"локальные рынки\"\nFROM default.operational_databook\nWHERE q >= toDate(1485085070) and q <= toDate(1642851470) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Продажи на локальных рынках Группы 3'\nand category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(value) as \"внешние рынки\"\nFROM $table\nWHERE q >= toDate($from) and q <= toDate($to) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Продажи на внешних рынках'\nand category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value) as \"внешние рынки\"\nFROM default.operational_databook\nWHERE q >= toDate(1485085070) and q <= toDate(1642851470) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Продажи на внешних рынках'\nand category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    }
   ]
  },
  {
   "title": "Продажи, кв/кв",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    (last_value(value)/neighbor(last_value(value), -1))-1\nFROM $table\nWHERE q >= toDate($from) and q <= toDate($to) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Итого консолидированные продажи'\nand category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    (last_value(value)/neighbor(last_value(value), -1))-1\nFROM default.operational_databook\nWHERE q >= toDate(1485087329) and q <= toDate(1642853729) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand name == 'Итого консолидированные продажи'\nand category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    }
   ]
  },
  {
   "title": "Консолидированные продажи, млн т",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(value),\n    name\nFROM $table\nWHERE q >= toDate($from) and q <= toDate($to) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand ( name == 'Полуфабрикаты 2'\nor name == 'Плоский прокат'\nor name == 'Сортовая продукция и метизы'\n) and category == 'Консолидированные продажи, млн т'\nGROUP BY q, name\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value),\n    name\nFROM default.operational_databook\nWHERE q >= toDate(1485086524) and q <= toDate(1642852924) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand ( name == 'Полуфабрикаты 2'\nor name == 'Плоский прокат'\nor name == 'Сортовая продукция и метизы'\n) and category == 'Консолидированные продажи, млн т'\nGROUP BY q, name\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    t.$dateCol as q,\n    last_value(t.value)/(last_value(t.value)+last_value(Semi.value)) as \"Доля готовой продукции\"\nFROM $table as t\nJOIN $table as Semi on (t.code = Semi.code and t.$dateCol == Semi.$dateCol and t.table == Semi.table and t.category == Semi.category) \nWHERE q >= toDate($from) and q <= toDate($to) and t.code == 'NLMK'\nand t.table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand t.name == 'Готовая продукция'\nand Semi.name == 'Полуфабрикаты 2'\nand t.category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    t.quarter as q,\n    last_value(t.value)/(last_value(t.value)+last_value(Semi.value)) as \"Доля готовой продукции\"\nFROM default.operational_databook as t\nJOIN default.operational_databook as Semi on (t.code = Semi.code and t.quarter == Semi.quarter and t.table == Semi.table and t.category == Semi.category) \nWHERE q >= toDate(1485087305) and q <= toDate(1642853705) and t.code == 'NLMK'\nand t.table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand t.name == 'Готовая продукция'\nand Semi.name == 'Полуфабрикаты 2'\nand t.category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    }
   ]
  },
  {
   "title": "Продажи готовой продукции, кв/кв",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    t.$dateCol as q,\n    (last_value(t.value)/neighbor(last_value(t.value), -1))-1\nFROM $table as t\nWHERE q >= toDate($from) and q <= toDate($to) and t.code == 'NLMK'\nand t.table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand t.name == 'Готовая продукция'\nand t.category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    t.quarter as q,\n    (last_value(t.value)/neighbor(last_value(t.value), -1))-1\nFROM default.operational_databook as t\nWHERE q >= toDate(1485087363) and q <= toDate(1642853763) and t.code == 'NLMK'\nand t.table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand t.name == 'Готовая продукция'\nand t.category == 'Консолидированные продажи, млн т'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    }
   ]
  },
  {
   "title": "Продажи сегментов, млн т",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(value),\n    name\nFROM $table\nWHERE q >= toDate($from) and q <= toDate($to) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand category == 'Продажи сегментов'\nand name != 'Для информации: продажи NBH'\nand name != 'Добыча и переработка сырья'\nGROUP BY q, name\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value),\n    name\nFROM default.operational_databook\nWHERE q >= toDate(1485082498) and q <= toDate(1642848898) and code == 'NLMK'\nand table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand category == 'Продажи сегментов'\nand name != 'Для информации: продажи NBH'\nand name != 'Добыча и переработка сырья'\nGROUP BY q, name\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    }
   ]
  },
  {
   "title": "Разница между производством стали и консолидированными продажами  тыс. тон",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT q, inventories/revenue as \"Inventories/Revenue per tonne of sales\" FROM (\n  SELECT\n    invent.$dateCol as q,\n    last_value(invent.value) as inventories,\n    last_value(revenue.value) as revenue\n  FROM $table as invent\n  JOIN $table as revenue ON (invent.sec_code == revenue.sec_code and invent.$dateCol == revenue.$dateCol)\n  WHERE invent.sec_code == 'NLMK' \n    and invent.indicator == 'Inventories'\n    and revenue.indicator == 'Revenue per tonne of sales, $/t'\n  GROUP BY q\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q, 2000 as inventories, 960 as revenue)\n)\nORDER BY q",
     "rawQuery": "SELECT q, inventories/revenue as \"Inventories/Revenue per tonne of sales\" FROM (\n  SELECT\n    invent.quarter as q,\n    last_value(invent.value) as inventories,\n    last_value(revenue.value) as revenue\n  FROM default.financial_ratios as invent\n  JOIN default.financial_ratios as revenue ON (invent.sec_code == revenue.sec_code and invent.quarter == revenue.quarter)\n  WHERE invent.sec_code == 'NLMK' \n    and invent.indicator == 'Inventories'\n    and revenue.indicator == 'Revenue per tonne of sales, $/t'\n  GROUP BY q\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 1, now()))) as q, 2000 as inventories, 960 as revenue)\n)\nORDER BY q",
     "round": "0s",
     "table": "financial_ratios"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    sales.quarter as q,\n    (last_value(production.value) - last_value(sales.value))*1000 as \"not sales\"\nFROM $table as sales\nLEFT JOIN $table as production ON sales.quarter == production.quarter and sales.code == production.code\nand sales.table = production.table\nWHERE q >= toDate($from) and q <= toDate($to) and sales.code == 'NLMK'\nand sales.table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand sales.name == 'Итого консолидированные продажи'\nand sales.category == 'Консолидированные продажи, млн т'\nand production.name == 'Производство стали (без NBH)'\nand production.category == 'Группа НЛМК'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    sales.quarter as q,\n    (last_value(production.value) - last_value(sales.value))*1000 as \"not sales\"\nFROM default.operational_databook as sales\nLEFT JOIN default.operational_databook as production ON sales.quarter == production.quarter and sales.code == production.code\nand sales.table = production.table\nWHERE q >= toDate(1548225194) and q <= toDate(1642919594) and sales.code == 'NLMK'\nand sales.table == 'КЛЮЧЕВЫЕ ОПЕРАЦИОННЫЕ ПОКАЗАТЕЛИ'\nand sales.name == 'Итого консолидированные продажи'\nand sales.category == 'Консолидированные продажи, млн т'\nand production.name == 'Производство стали (без NBH)'\nand production.category == 'Группа НЛМК'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "operational_databook"
    }
   ]
  },
  { "title": "TRANSAQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Price History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avgWeighted(close, volume) as price\nFROM $table\n\nWHERE\n    $timeFilter\n    and sec_code = 'NLMK'\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 604800) * 604800) * 1000 as t,\n    avgWeighted(close, volume) as price\nFROM default.candles\n\nWHERE\n    date >= toDateTime(1520176154) AND date <= toDateTime(1636038554)\n    and sec_code = 'MAGN'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "candles"
    }
   ]
  },
  {
   "title": "Price History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * FROM (SELECT\n    toDate(toStartOfQuarter(date_add(day, 44 , date))) as q,\n    avgWeighted(close, volume) as \"Stock price avg\"\nFROM $table\nWHERE\n    $timeFilter and sec_code == 'NLMK' and period == 5\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , $forecast_price))\nORDER BY q",
     "rawQuery": "select * FROM (SELECT\n    toDate(toStartOfQuarter(date_add(day, 44 , date))) as q,\n    avgWeighted(close, volume) as \"Stock price avg\"\nFROM default.candles\nWHERE\n    date >= toDateTime(1579709021) AND date <= toDateTime(1642867421) and sec_code == 'NLMK' and period == 5\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 3, now()))) as q , 230))\nORDER BY q",
     "round": "0s",
     "table": "candles"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * from (select p.q, (p.price*$shares)/((t.value*74)*4) as \"3M EV/EBITDA\" FROM (\nSELECT\n    toDate(toStartOfQuarter(date_add(day, 44 , date))) as q,\n    avgWeighted(close, volume) as price\nFROM candles\nWHERE sec_code == 'NLMK' and period == 5 and $dateTimeCol >= toDate($from) and $dateTimeCol <= toDate($to)\nGROUP BY q) as p\nLEFT JOIN $table as t ON p.q == t.quarter\nWHERE t.indicator == 'EBITDA' and t.sec_code == 'NLMK' and $dateCol >= toDate($from) and $dateCol <= toDate($to)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , $forecast_price*$shares/(2115*74*4)))\nORDER by q",
     "rawQuery": "select * from (select p.q, (p.price*5993.23)/((t.value*74)*4) as \"3M EV/EBITDA\" FROM (\nSELECT\n    toDate(toStartOfQuarter(date_add(day, 44 , date))) as q,\n    avgWeighted(close, volume) as price\nFROM candles\nWHERE sec_code == 'NLMK' and period == 5 and date >= toDate(1579709021) and date <= toDate(1642867421)\nGROUP BY q) as p\nLEFT JOIN default.financial_highlights as t ON p.q == t.quarter\nWHERE t.indicator == 'EBITDA' and t.sec_code == 'NLMK' and quarter >= toDate(1579709021) and quarter <= toDate(1642867421)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 230*5993.23/(2115*74*4)))\nORDER by q",
     "round": "0s",
     "table": "financial_highlights"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select * from (select p.q, (p.price*$shares)/((t.value*74)) as \"12M EV/EBITDA\" FROM (\nSELECT\n    toDate(toStartOfQuarter(date_add(day, 44 , date))) as q,\n    avgWeighted(close, volume) as price\nFROM candles\nWHERE sec_code == 'NLMK' and period == 5 and $dateTimeCol >= toDate($from) and $dateTimeCol <= toDate($to)\nGROUP BY q) as p\nLEFT JOIN $table as t ON p.q == t.quarter\nWHERE t.indicator == '12M EBITDA' and t.sec_code == 'NLMK' and $dateCol >= toDate($from) and $dateCol <= toDate($to)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , $forecast_price*$shares/((5510+2115)*74)))\nORDER by q",
     "rawQuery": "select * from (select p.q, (p.price*5993.23)/((t.value*74)) as \"12M EV/EBITDA\" FROM (\nSELECT\n    toDate(toStartOfQuarter(date_add(day, 44 , date))) as q,\n    avgWeighted(close, volume) as price\nFROM candles\nWHERE sec_code == 'NLMK' and period == 5 and date >= toDate(1579709021) and date <= toDate(1642867421)\nGROUP BY q) as p\nLEFT JOIN default.financial_highlights as t ON p.q == t.quarter\nWHERE t.indicator == '12M EBITDA' and t.sec_code == 'NLMK' and quarter >= toDate(1579709021) and quarter <= toDate(1642867421)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 230*5993.23/((5510+2115)*74)))\nORDER by q",
     "round": "0s",
     "table": "financial_highlights"
    },
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avgWeighted(close, volume) as \"Price close\"\nFROM $table\nWHERE\n    $timeFilter\n    and sec_code == 'NLMK' and period == 5\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(date), 604800) * 604800) * 1000 as t,\n    avgWeighted(close, volume) as \"Price close\"\nFROM default.candles\nWHERE\n    date >= toDateTime(1579709021) AND date <= toDateTime(1642867421)\n    and sec_code == 'NLMK' and period == 5\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "candles"
    }
   ]
  },
  { "title": "HIGHLIGHTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Динамика Выручки и EBITDA",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select quarter_name, CAPEX, EBITDA, Revenue from (\n  select $dateCol as q,\n         last_value(multiIf(equals(has(array('CAPEX','Purchases and construction of property, plant and equipment'), indicator), 1), value, NULL)) as CAPEX,\n         last_value(multiIf(equals(has(array('EBITDA'), indicator), 1), value, NULL)) as EBITDA,\n         last_value(multiIf(equals(has(array('REVENUE'), indicator), 1), value, NULL)) as Revenue,\n         quarter_name\n  from $table\n  where sec_code == 'NLMK' and $dateCol >= toDate($from) and $dateCol <= toDate($to)\n  group by quarter_name, $dateCol\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , -340, 2115, 4284, 'Q4 2021' as quarter_name)\n)\nWHERE q >= toDate($from) and q <= toDate($to)\norder by q\n\n",
     "rawQuery": "select quarter_name, CAPEX, EBITDA, Revenue from (\n  select quarter as q,\n         last_value(multiIf(equals(has(array('CAPEX','Purchases and construction of property, plant and equipment'), indicator), 1), value, NULL)) as CAPEX,\n         last_value(multiIf(equals(has(array('EBITDA'), indicator), 1), value, NULL)) as EBITDA,\n         last_value(multiIf(equals(has(array('REVENUE'), indicator), 1), value, NULL)) as Revenue,\n         quarter_name\n  from default.financial_highlights\n  where sec_code == 'NLMK' and quarter >= toDate(1579709897) and quarter <= toDate(1642868297)\n  group by quarter_name, quarter\n  UNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , -340, 2115, 4284, 'Q4 2021' as quarter_name)\n)\nWHERE q >= toDate(1579709897) and q <= toDate(1642868297)\norder by q",
     "round": "0s",
     "table": "financial_highlights"
    }
   ]
  },
  {
   "title": "Динамика Свободного денежного потока",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select quarter_name,\n       last_value(multiIf(equals(indicator,'Free cash flow'), value, NULL)) as FCF,\n       last_value(multiIf(equals(indicator,'Dividends to shareholders'), value, NULL)) as Dividends,\n       last_value(multiIf(equals(has(array('CAPEX','Purchases and construction of property, plant and equipment'), indicator), 1), value, NULL)) as CAPEX\nfrom $table where sec_code == 'NLMK' and $dateCol >= toDate($from) and $dateCol <= toDate($to)\ngroup by quarter_name, $dateCol\norder by $dateCol\n\n\n",
     "rawQuery": "select quarter_name,\n       last_value(multiIf(equals(indicator,'Free cash flow'), value, NULL)) as FCF,\n       last_value(multiIf(equals(indicator,'Dividends to shareholders'), value, NULL)) as Dividends,\n       last_value(multiIf(equals(has(array('CAPEX','Purchases and construction of property, plant and equipment'), indicator), 1), value, NULL)) as CAPEX\nfrom default.financial_highlights where sec_code == 'NLMK' and quarter >= toDate(1548187730) and quarter <= toDate(1642882130)\ngroup by quarter_name, quarter\norder by quarter",
     "round": "0s",
     "table": "financial_highlights"
    }
   ]
  },
  {
   "title": "EBITDA/т и цена реализации металлопродукции USD/т",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT q, indicator, last_value(v)  FROM (SELECT\n    $dateCol as q,\n    indicator,\n    last_value(value) as v\nFROM $table\nWHERE sec_code == 'NLMK'and has(array('Cash cost of slabs (USD/t)', 'Revenue per tonne of sales, $/t', 'EBITDA per tonne of sales, $/t'), indicator) == 1 \nGROUP BY q,indicator\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,'Revenue per tonne of sales, $/t', 960)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,'Cash cost of slabs (USD/t)', 252-16)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,'EBITDA per tonne of sales, $/t', (960.0-252+16-250)))\nWHERE q >= toDate($from) and q <= toDate($to)\nGROUP BY q, indicator\nORDER BY q, indicator",
     "rawQuery": "SELECT q, indicator, last_value(v)  FROM (SELECT\n    quarter as q,\n    indicator,\n    last_value(value) as v\nFROM default.financial_ratios\nWHERE sec_code == 'NLMK'and has(array('Cash cost of slabs (USD/t)', 'Revenue per tonne of sales, $/t', 'EBITDA per tonne of sales, $/t'), indicator) == 1 \nGROUP BY q,indicator\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,'Revenue per tonne of sales, $/t', 960)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,'Cash cost of slabs (USD/t)', 252-16)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,'EBITDA per tonne of sales, $/t', (960.0-252+16-250)))\nWHERE q >= toDate(1579708183) and q <= toDate(1642866583)\nGROUP BY q, indicator\nORDER BY q, indicator",
     "round": "0s",
     "table": "financial_ratios"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT r.quarter, last_value(r.value) - last_value(e.value) - last_value(s.value) as \"Other production cost\"\nFROM $table as r\nLEFT JOIN $table as e on e.quarter == r.quarter and e.sec_code == r.sec_code\nLEFT JOIN $table as s on s.quarter == r.quarter and s.sec_code == r.sec_code\nWHERE r.sec_code == 'NLMK' and s.indicator == 'Cash cost of slabs (USD/t) ' and e.indicator == 'EBITDA per tonne of sales, $/t' and r.indicator == 'Revenue per tonne of sales, $/t'\nand r.quarter >= toDate($from) and r.quarter <= toDate($to)\nGROUP BY r.quarter",
     "rawQuery": "SELECT r.quarter, last_value(r.value) - last_value(e.value) - last_value(s.value) as \"Other production cost\"\nFROM default.financial_ratios as r\nLEFT JOIN default.financial_ratios as e on e.quarter == r.quarter and e.sec_code == r.sec_code\nLEFT JOIN default.financial_ratios as s on s.quarter == r.quarter and s.sec_code == r.sec_code\nWHERE r.sec_code == 'NLMK' and s.indicator == 'Cash cost of slabs (USD/t) ' and e.indicator == 'EBITDA per tonne of sales, $/t' and r.indicator == 'Revenue per tonne of sales, $/t'\nand r.quarter >= toDate(1579708183) and r.quarter <= toDate(1642866583)\nGROUP BY r.quarter",
     "round": "0s",
     "table": "financial_ratios"
    }
   ]
  },
  {
   "title": "Оборотные активы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT q, indicator, last_value(v) FROM (SELECT\n    $dateCol as q,\n    indicator,\n    last_value(value) as v\nFROM $table\nWHERE sec_code == 'NLMK' and has(array('Trade and other accounts receivable','Inventories'), indicator) == 1\nGROUP BY q, indicator\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Trade and other accounts receivable' as indicator, 1800 as v)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Inventories' as indicator, 2000 as v))\nGROUP BY q, indicator\nORDER BY q, last_value(v)\n",
     "rawQuery": "SELECT q, indicator, last_value(v) FROM (SELECT\n    quarter as q,\n    indicator,\n    last_value(value) as v\nFROM default.financial_ratios\nWHERE sec_code == 'NLMK' and has(array('Trade and other accounts receivable','Inventories'), indicator) == 1\nGROUP BY q, indicator\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Trade and other accounts receivable' as indicator, 1800 as v)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Inventories' as indicator, 2000 as v))\nGROUP BY q, indicator\nORDER BY q, last_value(v)",
     "round": "0s",
     "table": "financial_ratios"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT q, sum(n.v)/(last_value(h.value)*4)*100 as \"NWC/(Revenue L3m*4) percent\"\nFROM (SELECT\n    $dateCol as q,\n    indicator,\n    last_value(value) as v\nFROM $table\nWHERE sec_code == 'NLMK' and has(array('Trade and other accounts receivable','Inventories'), indicator) == 1\nGROUP BY q, indicator\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Trade and other accounts receivable' as indicator, 1800 as v)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Inventories' as indicator, 2100 as v)) as n\nLEFT JOIN financial_highlights as h on h.quarter == n.q\nWHERE h.sec_code == 'NLMK' and h.indicator == 'REVENUE'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT q, sum(n.v)/(last_value(h.value)*4)*100 as \"NWC/(Revenue L3m*4) percent\"\nFROM (SELECT\n    quarter as q,\n    indicator,\n    last_value(value) as v\nFROM default.financial_ratios\nWHERE sec_code == 'NLMK' and has(array('Trade and other accounts receivable','Inventories'), indicator) == 1\nGROUP BY q, indicator\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Trade and other accounts receivable' as indicator, 1800 as v)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Inventories' as indicator, 2100 as v)) as n\nLEFT JOIN financial_highlights as h on h.quarter == n.q\nWHERE h.sec_code == 'NLMK' and h.indicator == 'REVENUE'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "financial_ratios"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    n.$dateCol as q,\n    last_value(n.value)/last_value(h.value)*100 as \"Increase in inventories of EBITDA percent\"\nFROM $table as n\nLEFT JOIN financial_highlights as h on h.$dateCol == n.$dateCol and n.sec_code == h.sec_code\nWHERE n.sec_code == 'NLMK' and n.indicator == 'Increase in inventories' and h.indicator == 'EBITDA'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    n.quarter as q,\n    last_value(n.value)/last_value(h.value)*100 as \"Increase in inventories of EBITDA percent\"\nFROM default.financial_highlights as n\nLEFT JOIN financial_highlights as h on h.quarter == n.quarter and n.sec_code == h.sec_code\nWHERE n.sec_code == 'NLMK' and n.indicator == 'Increase in inventories' and h.indicator == 'EBITDA'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "financial_highlights"
    }
   ]
  },
  {
   "title": "Структура продаж в тоннах по видам продукции",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT q, product, last_value(ton) FROM (SELECT\n    quarter as q,\n    product,\n    last_value(value) as ton\nFROM $table\nWHERE sec_code == 'NLMK' and has(array(\n'Semi-finished products',\n'Flat products',\n'Long products'), product) == 1\nGROUP BY q, product \nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Semi-finished products' as product, 1402 as ton)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Flat products' as product, 2330 as ton)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Long products' as product, 731 as ton))\nGROUP BY q, product\nORDER BY q, last_value(ton)\n",
     "rawQuery": "SELECT q, product, last_value(ton) FROM (SELECT\n    quarter as q,\n    product,\n    last_value(value) as ton\nFROM default.consolidated_sales_for_products\nWHERE sec_code == 'NLMK' and has(array(\n'Semi-finished products',\n'Flat products',\n'Long products'), product) == 1\nGROUP BY q, product \nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Semi-finished products' as product, 1402 as ton)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Flat products' as product, 2330 as ton)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 'Long products' as product, 731 as ton))\nGROUP BY q, product\nORDER BY q, last_value(ton)",
     "round": "0s",
     "table": "consolidated_sales_for_products"
    }
   ]
  },
  {
   "title": "Структура продаж в тоннах по регионам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    product,\n    last_value(value) as ton\nFROM $table\nWHERE sec_code == 'NLMK' and has(array(\n'Russia',\n'EU',\n'M. East (incl. Turkey)', 'North America', 'South East Asia', 'Central and South America', 'CIS', 'Other'), product) == 1\nGROUP BY q, product \nORDER BY q, ton desc",
     "rawQuery": "SELECT\n    quarter as q,\n    product,\n    last_value(value) as ton\nFROM default.consolidated_sales_for_products\nWHERE sec_code == 'NLMK' and has(array(\n'Russia',\n'EU',\n'M. East (incl. Turkey)', 'North America', 'South East Asia', 'Central and South America', 'CIS', 'Other'), product) == 1\nGROUP BY q, product \nORDER BY q, ton desc",
     "round": "0s",
     "table": "consolidated_sales_for_products"
    }
   ]
  },
  { "title": "Production & Sales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Цены прокатной продукции за тонну",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT q, v as \"Revenue per tonne\" FROM (SELECT\n    $dateCol as q,\n    last_value(value) as v\nFROM $table\nWHERE sec_code == 'NLMK' and indicator == 'Revenue per tonne of sales, $/t'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,960 as v))\nORDER BY q",
     "rawQuery": "SELECT q, v as \"Revenue per tonne\" FROM (SELECT\n    quarter as q,\n    last_value(value) as v\nFROM default.financial_ratios\nWHERE sec_code == 'NLMK' and indicator == 'Revenue per tonne of sales, $/t'\nGROUP BY q\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,960 as v))\nORDER BY q",
     "round": "0s",
     "table": "financial_ratios"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (SELECT\n  quarter as q,\n  floor(revenue.value*1000/sales.value) as \"Longs\"\nFROM consolidated_sales_for_products as sales\nLEFT JOIN (SELECT sec_code,\n                    quarter as q,\n                    last_value(value) as value\n                FROM default.revenue_structure\n                WHERE sec_code == 'NLMK' and structure == 'Longs'\n                GROUP BY q, sec_code\n) as revenue\nON revenue.sec_code = sales.sec_code and revenue.q = sales.quarter \nwhere sales.product == 'Long products' and sec_code == 'NLMK'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , $forecast_PriceAverage - 290)\n)\nORDER BY q\n",
     "rawQuery": "SELECT * FROM (SELECT\n  quarter as q,\n  floor(revenue.value*1000/sales.value) as \"Longs\"\nFROM consolidated_sales_for_products as sales\nLEFT JOIN (SELECT sec_code,\n                    quarter as q,\n                    last_value(value) as value\n                FROM default.revenue_structure\n                WHERE sec_code == 'NLMK' and structure == 'Longs'\n                GROUP BY q, sec_code\n) as revenue\nON revenue.sec_code = sales.sec_code and revenue.q = sales.quarter \nwhere sales.product == 'Long products' and sec_code == 'NLMK'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 980 - 290)\n)\nORDER BY q",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (SELECT\n  quarter as q,\n  floor(revenue.value/sales.value * 1000) as \"HRC\"\nFROM consolidated_sales_for_products as sales\nLEFT JOIN (SELECT sec_code, q, sum(v) as value\n           FROM (\n                SELECT\n                    sec_code,\n                    quarter as q,\n                    structure,\n                    last_value(value) as v\n                FROM default.revenue_structure\n                WHERE sec_code == 'NLMK'\n                  and has(array('HRC'), structure) == 1\n                GROUP BY q, structure, sec_code)\n           GROUP BY q, sec_code\n) as revenue\nON revenue.sec_code = sales.sec_code and revenue.q = sales.quarter\nwhere sales.product == 'HRC' and sec_code == 'NLMK'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , $forecast_PriceAverage)\n)\nORDER BY q\n",
     "rawQuery": "SELECT * FROM (SELECT\n  quarter as q,\n  floor(revenue.value/sales.value * 1000) as \"HRC\"\nFROM consolidated_sales_for_products as sales\nLEFT JOIN (SELECT sec_code, q, sum(v) as value\n           FROM (\n                SELECT\n                    sec_code,\n                    quarter as q,\n                    structure,\n                    last_value(value) as v\n                FROM default.revenue_structure\n                WHERE sec_code == 'NLMK'\n                  and has(array('HRC'), structure) == 1\n                GROUP BY q, structure, sec_code)\n           GROUP BY q, sec_code\n) as revenue\nON revenue.sec_code = sales.sec_code and revenue.q = sales.quarter\nwhere sales.product == 'HRC' and sec_code == 'NLMK'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 980)\n)\nORDER BY q",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (\nSELECT\n  sales.quarter as q,\n  floor(revenue.value/sales.value * 1000) as \"Slabs\"\nFROM consolidated_sales_for_products as sales\nLEFT JOIN (\n  SELECT quarter, last_value(value) as value\n  FROM revenue_structure\n  WHERE sec_code == 'NLMK' and structure == 'Slabs'\n  GROUP BY quarter) as revenue ON revenue.quarter = sales.quarter\nWHERE sales.product == 'Slabs' and sales.sec_code == 'NLMK'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , $forecast_PriceAverage - 280)\n)\nORDER BY q\n",
     "rawQuery": "SELECT * FROM (\nSELECT\n  sales.quarter as q,\n  floor(revenue.value/sales.value * 1000) as \"Slabs\"\nFROM consolidated_sales_for_products as sales\nLEFT JOIN (\n  SELECT quarter, last_value(value) as value\n  FROM revenue_structure\n  WHERE sec_code == 'NLMK' and structure == 'Slabs'\n  GROUP BY quarter) as revenue ON revenue.quarter = sales.quarter\nWHERE sales.product == 'Slabs' and sales.sec_code == 'NLMK'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 980 - 280)\n)\nORDER BY q",
     "round": "0s"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (SELECT\n  quarter as q,\n  floor(revenue.value/sales.value * 1000) as \"HVA\"\nFROM $table as revenue\nLEFT JOIN (SELECT sec_code, quarter, sum(v) as value\n           FROM (\n                SELECT\n                    sec_code,\n                    quarter,\n                    product,\n                    last_value(value) as v\n                FROM consolidated_sales_for_products\n                WHERE sec_code == 'NLMK'\n                  and has(array('Plates', 'CRC', 'HDG', 'Coated', 'Dynamo', 'Transformer', 'Metalware'), product) == 1\n                GROUP BY quarter, product, sec_code)\n           GROUP BY quarter, sec_code\n) as sales\nON revenue.sec_code = sales.sec_code and revenue.quarter = sales.quarter\nwhere revenue.structure == 'High value added products' and sec_code == 'NLMK' and revenue.$dateCol >= toDate($from) and revenue.$dateCol <= toDate($to)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , $forecast_PriceAverage + 120)\n)\nORDER BY q\n",
     "rawQuery": "SELECT * FROM (SELECT\n  quarter as q,\n  floor(revenue.value/sales.value * 1000) as \"HVA\"\nFROM default.revenue_structure as revenue\nLEFT JOIN (SELECT sec_code, quarter, sum(v) as value\n           FROM (\n                SELECT\n                    sec_code,\n                    quarter,\n                    product,\n                    last_value(value) as v\n                FROM consolidated_sales_for_products\n                WHERE sec_code == 'NLMK'\n                  and has(array('Plates', 'CRC', 'HDG', 'Coated', 'Dynamo', 'Transformer', 'Metalware'), product) == 1\n                GROUP BY quarter, product, sec_code)\n           GROUP BY quarter, sec_code\n) as sales\nON revenue.sec_code = sales.sec_code and revenue.quarter = sales.quarter\nwhere revenue.structure == 'High value added products' and sec_code == 'NLMK' and revenue.quarter >= toDate(1579708152) and revenue.quarter <= toDate(1642866552)\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q , 980 + 120)\n)\nORDER BY q",
     "round": "0s",
     "table": "revenue_structure"
    },
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(toStartOfQuarter(date_add(month, $price_lag_months, date))) as q,\n    avg(close) as HRC_FOB_CHINA\nFROM $table\nWHERE code == 'MHCc1' and $dateCol >= toDate($from) and $dateCol <= toDate($to)\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    toDate(toStartOfQuarter(date_add(month, 3, date))) as q,\n    avg(close) as HRC_FOB_CHINA\nFROM default.stock_prices\nWHERE code == 'MHCc1' and date >= toDate(1579708152) and date <= toDate(1642866552)\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    }
   ]
  },
  {
   "title": "Корреляция индекса Фьючерс на кокс. уголь и затраты на уголь",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(week, 17, date))) as q,\n    avg(close)/17.4 as \"Coking Coal CHINA\"\nfrom $table\nWHERE code == 'DJMc1' and q >= toDate($from) and q <= toDate($to)\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(week, 17, date))) as q,\n    avg(close)/17.4 as \"Coking Coal CHINA\"\nfrom default.stock_prices\nWHERE code == 'DJMc1' and q >= toDate(1579712211) and q <= toDate(1642870611)\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (SELECT\n  quarter as q,\n  floor(revenue.value*1000/sales.value) as \"Coke and coal price\"\nFROM revenue_structure as sales\nLEFT JOIN (SELECT sec_code,\n                    quarter as q,\n                    last_value(value) as value\n                FROM default.cost_of_sales_structure\n                WHERE sec_code == 'NLMK' and structure == 'Coke and coal'\n           GROUP BY q, sec_code\n) as revenue\nON revenue.sec_code = sales.sec_code and revenue.q = sales.quarter\nwhere sales.structure == 'TOTAL SALES'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,  100)\n)\nWHERE q >= toDate($from) and q <= toDate($to)\nORDER BY q\n",
     "rawQuery": "SELECT * FROM (SELECT\n  quarter as q,\n  floor(revenue.value*1000/sales.value) as \"Coke and coal price\"\nFROM revenue_structure as sales\nLEFT JOIN (SELECT sec_code,\n                    quarter as q,\n                    last_value(value) as value\n                FROM default.cost_of_sales_structure\n                WHERE sec_code == 'NLMK' and structure == 'Coke and coal'\n           GROUP BY q, sec_code\n) as revenue\nON revenue.sec_code = sales.sec_code and revenue.q = sales.quarter\nwhere sales.structure == 'TOTAL SALES'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,  100)\n)\nWHERE q >= toDate(1579712211) and q <= toDate(1642870611)\nORDER BY q",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Корреляция индекса ЖРС и железной части кеш-кост сляба",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(month, $price_lag_months+1, date))) as q,\n    avg(close) as 62PercFe\nfrom $table\nWHERE code == 'SGXIOSc1'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(month, 3+1, date))) as q,\n    avg(close) as 62PercFe\nfrom default.stock_prices\nWHERE code == 'SGXIOSc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as Index62Fe\nFROM $table\nWHERE product == 'Fe'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as Index62Fe\nFROM default.fob_prices\nWHERE product == 'Fe'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "fob_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM (SELECT\n  quarter as q,\n  floor(revenue.value*1000/sales.value) as \"Iron ore materials price\"\nFROM revenue_structure as sales\nLEFT JOIN (SELECT sec_code,\n                    quarter as q,\n                    last_value(value) as value\n                FROM default.cost_of_sales_structure\n                WHERE sec_code == 'NLMK' and structure == 'Iron ore materials'\n           GROUP BY q, sec_code\n) as revenue\nON revenue.sec_code = sales.sec_code and revenue.q = sales.quarter\nwhere sales.structure == 'TOTAL SALES'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,  120)\n)\nWHERE q >= toDate($from) and q <= toDate($to)\nORDER BY q",
     "rawQuery": "SELECT * FROM (SELECT\n  quarter as q,\n  floor(revenue.value*1000/sales.value) as \"Iron ore materials price\"\nFROM revenue_structure as sales\nLEFT JOIN (SELECT sec_code,\n                    quarter as q,\n                    last_value(value) as value\n                FROM default.cost_of_sales_structure\n                WHERE sec_code == 'NLMK' and structure == 'Iron ore materials'\n           GROUP BY q, sec_code\n) as revenue\nON revenue.sec_code = sales.sec_code and revenue.q = sales.quarter\nwhere sales.structure == 'TOTAL SALES'\nUNION ALL (SELECT toDate(toStartOfQuarter(date_add(month, 2, now()))) as q ,  120)\n)\nWHERE q >= toDate(1579712354) and q <= toDate(1642870754)\nORDER BY q",
     "round": "0s",
     "table": "material_cost_structure"
    }
   ]
  },
  {
   "title": "Средневзвешенная цена готовой продукции  в дол. США",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(month, $price_lag_months, date))) as q,\n    avg(close) as US_HRC\nfrom $table\nWHERE code == 'HRCc1'\nGROUP BY q\nORDER BY q",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(month, 3, date))) as q,\n    avg(close) as US_HRC\nfrom default.stock_prices\nWHERE code == 'HRCc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(toStartOfQuarter(date_add(month, $price_lag_months, date))) as q,\n    avg(close) as HRC_FOB_CHINA\nFROM $table\n\nWHERE code == 'MHCc1'\n\nGROUP BY q\n\nORDER BY q\n",
     "rawQuery": "SELECT\n    toDate(toStartOfQuarter(date_add(month, 3, date))) as q,\n    avg(close) as HRC_FOB_CHINA\nFROM default.stock_prices\n\nWHERE code == 'MHCc1'\n\nGROUP BY q\n\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(month, $price_lag_months, date))) as q,\n    avg(M3) as LME_HC\nfrom $table\nWHERE code == 'HC'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(month, 3, date))) as q,\n    avg(M3) as LME_HC\nfrom default.lme_closing_prices\nWHERE code == 'HC'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "lme_closing_prices"
    },
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(month, $price_lag_months, date))) as q,\n    avg(M12) as LME_HU\nfrom $table\nWHERE code == 'HU'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(month, 3, date))) as q,\n    avg(M12) as LME_HU\nfrom default.lme_closing_prices\nWHERE code == 'HU'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "lme_closing_prices"
    },
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(month, $price_lag_months, date))) as q,\n    avg(close)/8 as SHHCc1\nfrom $table\nWHERE code == 'SHHCc1'\nGROUP BY q\nORDER BY q",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(month, 3, date))) as q,\n    avg(close)/8 as SHHCc1\nfrom default.stock_prices\nWHERE code == 'SHHCc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as FlatHotRolled\nFROM $table\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as FlatHotRolled\nFROM default.prices_for_products\nWHERE product == 'Flat hot-rolled products'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "prices_for_products"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as MMK_CHINA\nFROM $table\nWHERE product == 'HRC FOB CHINA'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as MMK_CHINA\nFROM default.fob_prices\nWHERE product == 'HRC FOB CHINA'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "fob_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as MMK_BLACK_SEA\nFROM $table\nWHERE product == 'HRC FOB Black sea'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as MMK_BLACK_SEA\nFROM default.fob_prices\nWHERE product == 'HRC FOB Black sea'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "fob_prices"
    }
   ]
  },
  { "title": "COS breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Затраты,  USD mln",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    structure,\n    last_value(value)\nFROM $table\nWHERE sec_code == 'NLMK' and structure != 'Other expenses and changes in inventories' and q >= toDate($from) and q <= toDate($to)\nGROUP BY q, structure\nORDER BY q, sum(value) desc\n",
     "rawQuery": "SELECT\n    quarter as q,\n    structure,\n    last_value(value)\nFROM default.cost_of_sales_structure\nWHERE sec_code == 'NLMK' and structure != 'Other expenses and changes in inventories' and q >= toDate(1574978277) and q <= toDate(1646074799)\nGROUP BY q, structure\nORDER BY q, sum(value) desc",
     "round": "0s",
     "table": "cost_of_sales_structure"
    }
   ]
  },
  {
   "title": "Корреляция индекса ЖРС и железной части кеш-кост сляба",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select\n    toDate(toStartOfQuarter(date_add(month, $price_lag_months, date))) as q,\n    avg(close) as 62PercFe\nfrom $table\nWHERE code == 'SGXIOSc1'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "select\n    toDate(toStartOfQuarter(date_add(month, 4, date))) as q,\n    avg(close) as 62PercFe\nfrom default.stock_prices\nWHERE code == 'SGXIOSc1'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "stock_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(price) as Index62Fe\nFROM $table\nWHERE product == 'Fe'\nGROUP BY q\nORDER BY q\n",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(price) as Index62Fe\nFROM default.fob_prices\nWHERE product == 'Fe'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "fob_prices"
    },
    {
     "database": "default",
     "dateColDataType": "quarter",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    quarter as q,\n    last_value(value)\nFROM $table WHERE sec_code == 'NLMK' and structure == 'Iron ore materials'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    quarter as q,\n    last_value(value)\nFROM default.cost_of_sales_structure WHERE sec_code == 'NLMK' and structure == 'Iron ore materials'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "cost_of_sales_structure"
    }
   ]
  },
  {
   "title": "Экспорт  России",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    name,\n    last_value(quantity)\nFROM $table\nWHERE code == '72 (кроме 7201-7204)' or code=='7208-7212' \nGROUP BY q,name\nORDER BY q\n",
     "rawQuery": "SELECT\n    month as q,\n    name,\n    last_value(quantity)\nFROM default.export_goods\nWHERE code == '72 (кроме 7201-7204)' or code=='7208-7212' \nGROUP BY q,name\nORDER BY q",
     "round": "0s",
     "table": "export_goods"
    }
   ]
  },
  {
   "title": "Экспорт ЛИПЕЦКАЯ область, млн. долл. США",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $dateCol as q,\n    last_value(if(runningDifference(export)>0,runningDifference(export),export)) as Export,\n    last_value(if(runningDifference(cis)>0,runningDifference(cis), cis)) as \"CIS\"\nFROM $table\n\nwhere name = 'ЛИПЕЦКАЯ ОБЛАСТЬ'\nGROUP BY q\nORDER BY q",
     "rawQuery": "SELECT\n    month as q,\n    last_value(if(runningDifference(export)>0,runningDifference(export),export)) as Export,\n    last_value(if(runningDifference(cis)>0,runningDifference(cis), cis)) as \"CIS\"\nFROM default.export_regions\n\nwhere name = 'ЛИПЕЦКАЯ ОБЛАСТЬ'\nGROUP BY q\nORDER BY q",
     "round": "0s",
     "table": "export_regions"
    }
   ]
  }
 ]
}