{
 "title": "VTB finance results",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Чистая прибыль, млрд. руб.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select if(msfo.v == 0, rsbu.month, msfo.month) as month, msfo.v as \"Чистая прибыль(МСФО)\" , rsbu.v as \"Чистая прибыль(РСБУ)\" from (select month, last_value(value) as v\n    from default.finance_results\n    where standard == 'МСФО' and category ==  'Ключевые показатели P&L' and has(array('Чистая прибыль / (убыток)', 'Чистая прибыль'), name)\n    group by month\n    order by month\n    UNION ALL (SELECT toDate(parseDateTimeBestEffortOrNull('2021-05-30')) as month, 25.0 as v)\n                                                                                                                                   ) as msfo\nFULL JOIN (select month, last_value(value) as v\n    from default.finance_results\n    where standard == 'РСБУ' and has(array('Чистая прибыль / (убыток)', 'Чистая прибыль'), name) == 1\n    group by month\n    order by month) as rsbu on (msfo.month == rsbu.month)\norder by month",
     "rawQuery": "select if(msfo.v == 0, rsbu.month, msfo.month) as month, msfo.v as \"Чистая прибыль(МСФО)\" , rsbu.v as \"Чистая прибыль(РСБУ)\" from (select month, last_value(value) as v\n    from default.finance_results\n    where standard == 'МСФО' and category ==  'Ключевые показатели P&L' and has(array('Чистая прибыль / (убыток)', 'Чистая прибыль'), name)\n    group by month\n    order by month\n    UNION ALL (SELECT toDate(parseDateTimeBestEffortOrNull('2021-05-30')) as month, 25.0 as v)\n                                                                                                                                   ) as msfo\nFULL JOIN (select month, last_value(value) as v\n    from default.finance_results\n    where standard == 'РСБУ' and has(array('Чистая прибыль / (убыток)', 'Чистая прибыль'), name) == 1\n    group by month\n    order by month) as rsbu on (msfo.month == rsbu.month)\norder by month",
     "round": "0s",
     "table": "finance_results"
    },
    {
     "database": "default",
     "dateTimeColDataType": "date",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avgWeighted(close*1000, volume)/1000 as \"Stock price\"\nFROM $table\nWHERE\n    date >= toDate($from) AND date <= toDate($to)\n    and sec_code == 'VTBR' and period == '5' \nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    toStartOfInterval(date, INTERVAL 7 day) as t,\n    avgWeighted(close*1000, volume)/1000 as \"Stock price\"\nFROM default.candles\nWHERE\n    date >= toDate(1542874073) AND date <= toDate(1637568473)\n    and sec_code == 'VTBR' and period == '5' \nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "candles"
    }
   ]
  },
  {
   "title": "Ключевые показатели P&L по МСФО",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "ЧОД до резервов, млрд. руб.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select $dateCol,\nlast_value(multiIf(equals(name,'ЧОД до резервов'), value, NULL)) as \"ЧОД\",\n       last_value(multiIf(equals(name,'Чистые процентные доходы'), value, NULL)) as \"ЧПД\",\n       last_value(multiIf(equals(name,'Чистые комиссионные доходы'), value, NULL)) as \"ЧКД\",\n       last_value(multiIf(equals(name,'Прочие операционные доходы'), value, NULL)) as \"ПОД\",\n       last_value(multiIf(has(array('Создание резервов под кредитные убытки и прочие резервы', 'Создание резерва под обесценение', 'Создание резерва под кредитные убытки и прочие резервы'), name) == 1, value, NULL)) as \"Резервы\",\n       last_value(multiIf(equals(name,'Расходы на содержание персонала и административные расходы'), value, NULL)) as \"Расходы\"\nfrom $table\nwhere code == 'VTBR' and standard == 'МСФО' and category ==  'Ключевые показатели P&L'\ngroup by $dateCol\norder by $dateCol",
     "rawQuery": "select month,\nlast_value(multiIf(equals(name,'ЧОД до резервов'), value, NULL)) as \"ЧОД\",\n       last_value(multiIf(equals(name,'Чистые процентные доходы'), value, NULL)) as \"ЧПД\",\n       last_value(multiIf(equals(name,'Чистые комиссионные доходы'), value, NULL)) as \"ЧКД\",\n       last_value(multiIf(equals(name,'Прочие операционные доходы'), value, NULL)) as \"ПОД\",\n       last_value(multiIf(has(array('Создание резервов под кредитные убытки и прочие резервы', 'Создание резерва под обесценение', 'Создание резерва под кредитные убытки и прочие резервы'), name) == 1, value, NULL)) as \"Резервы\",\n       last_value(multiIf(equals(name,'Расходы на содержание персонала и административные расходы'), value, NULL)) as \"Расходы\"\nfrom default.finance_results\nwhere code == 'VTBR' and standard == 'МСФО' and category ==  'Ключевые показатели P&L'\ngroup by month\norder by month",
     "round": "0s",
     "table": "finance_results"
    }
   ]
  },
  {
   "title": "Чистая прибыль, млрд. руб.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select $dateCol,\n       last_value(multiIf(has(array('Чистая прибыль / (убыток)', 'Чистая прибыль'), name) == 1, value, NULL)) as \"Чистая прибыль\",\n       last_value(multiIf(equals(name,'ЧОД до резервов'), value, NULL)) as \"ЧОД\",\n       last_value(multiIf(has(array('Создание резервов под кредитные убытки и прочие резервы', 'Создание резерва под обесценение', 'Создание резерва под кредитные убытки и прочие резервы'), name) == 1, value, NULL)) as \"Резервы\"\nfrom $table\nwhere code == 'VTBR' and standard == 'МСФО'   and category ==  'Ключевые показатели P&L'\ngroup by $dateCol\norder by $dateCol\n",
     "rawQuery": "select month,\n       last_value(multiIf(has(array('Чистая прибыль / (убыток)', 'Чистая прибыль'), name) == 1, value, NULL)) as \"Чистая прибыль\",\n       last_value(multiIf(equals(name,'ЧОД до резервов'), value, NULL)) as \"ЧОД\",\n       last_value(multiIf(has(array('Создание резервов под кредитные убытки и прочие резервы', 'Создание резерва под обесценение', 'Создание резерва под кредитные убытки и прочие резервы'), name) == 1, value, NULL)) as \"Резервы\"\nfrom default.finance_results\nwhere code == 'VTBR' and standard == 'МСФО'   and category ==  'Ключевые показатели P&L'\ngroup by month\norder by month",
     "round": "0s",
     "table": "finance_results"
    }
   ]
  },
  {
   "title": "Прочие операционные доходы, млрд. руб.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select month, name, runningDifference(last_value(value))\nfrom default.finance_results\nwhere code == 'VTBR' and standard == 'МСФО'  and has(array('Прочие операционные доходы', 'Прочие операционные доходы и расходы'), category) == 1\ngroup by month, name\norder by month",
     "rawQuery": "select month, name, runningDifference(last_value(value))\nfrom default.finance_results\nwhere code == 'VTBR' and standard == 'МСФО'  and has(array('Прочие операционные доходы', 'Прочие операционные доходы и расходы'), category) == 1\ngroup by month, name\norder by month",
     "round": "0s",
     "table": "finance_results"
    }
   ]
  },
  {
   "title": "Чистые комиссионные доходы, млрд. руб.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select month, name, runningDifference(last_value(value))\nfrom default.finance_results\nwhere code == 'VTBR' and standard == 'МСФО'  and has(array('Чистые комиссионные доходы'), category) == 1\ngroup by month, name\norder by month",
     "rawQuery": "select month, name, runningDifference(last_value(value))\nfrom default.finance_results\nwhere code == 'VTBR' and standard == 'МСФО'  and has(array('Чистые комиссионные доходы'), category) == 1\ngroup by month, name\norder by month",
     "round": "0s",
     "table": "finance_results"
    }
   ]
  },
  {
   "title": "Ключевые показатели P&L по РСБУ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "ЧОД до резервов, млрд. руб.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select $dateCol,\n       last_value(multiIf(equals(name,'Чистые процентные доходы'), value, NULL)) as \"ЧПД\",\n       last_value(multiIf(equals(name,'Чистые комиссионные доходы'), value, NULL)) as \"ЧКД\",\n       last_value(multiIf(equals(name,'Прочие чистые операционные доходы'), value, NULL)) as \"ПОД\",\n       last_value(multiIf(has(array('Создание резервов под обесценение', 'Операционные расходы'), name) == 1, value, NULL)) as \"Резерв\"\nfrom $table\nwhere code == 'VTBR' and standard == 'РСБУ'\ngroup by $dateCol\norder by $dateCol\n",
     "rawQuery": "select month,\n       last_value(multiIf(equals(name,'Чистые процентные доходы'), value, NULL)) as \"ЧПД\",\n       last_value(multiIf(equals(name,'Чистые комиссионные доходы'), value, NULL)) as \"ЧКД\",\n       last_value(multiIf(equals(name,'Прочие чистые операционные доходы'), value, NULL)) as \"ПОД\",\n       last_value(multiIf(has(array('Создание резервов под обесценение', 'Операционные расходы'), name) == 1, value, NULL)) as \"Резерв\"\nfrom default.finance_results\nwhere code == 'VTBR' and standard == 'РСБУ'\ngroup by month\norder by month",
     "round": "0s",
     "table": "finance_results"
    }
   ]
  },
  {
   "title": "Прибыль по РСБУ, млрд. руб.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select $dateCol,\n       last_value(multiIf(equals(name,'Чистая прибыль'), value, NULL)) as \"Чистая прибыль\",\n       last_value(multiIf(equals(name,'Прибыль до налогообложения'), value, NULL)) as \"Прибыль\"\nfrom $table\nwhere code == 'VTBR' and standard == 'РСБУ'\ngroup by $dateCol\norder by $dateCol\n",
     "rawQuery": "select month,\n       last_value(multiIf(equals(name,'Чистая прибыль'), value, NULL)) as \"Чистая прибыль\",\n       last_value(multiIf(equals(name,'Прибыль до налогообложения'), value, NULL)) as \"Прибыль\"\nfrom default.finance_results\nwhere code == 'VTBR' and standard == 'РСБУ'\ngroup by month\norder by month",
     "round": "0s",
     "table": "finance_results"
    },
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select $dateCol, sum(value) as \"Доход-расход\"\nfrom $table\nwhere code == 'VTBR' and standard == 'РСБУ' and has(array('Чистые процентные доходы','Чистые комиссионные доходы','Прочие чистые операционные доходы','Создание резервов под обесценение','Расходы на содержание персонала и \n  административные расходы', 'Операционные расходы'), name) == 1\ngroup by $dateCol\norder by $dateCol\n",
     "rawQuery": "select month, sum(value) as \"Доход-расход\"\nfrom default.finance_results\nwhere code == 'VTBR' and standard == 'РСБУ' and has(array('Чистые процентные доходы','Чистые комиссионные доходы','Прочие чистые операционные доходы','Создание резервов под обесценение','Расходы на содержание персонала и \n  административные расходы', 'Операционные расходы'), name) == 1\ngroup by month\norder by month",
     "round": "0s",
     "table": "finance_results"
    }
   ]
  },
  {
   "title": "Рентабельность капитала (ROE)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "month",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select $dateCol, last_value(value) as ROE\nfrom $table\nwhere code == 'VTBR' and standard == 'РСБУ' and name == 'Рентабельность капитала (ROE)'\ngroup by $dateCol\norder by $dateCol\n",
     "rawQuery": "select month, last_value(value) as ROE\nfrom default.finance_results\nwhere code == 'VTBR' and standard == 'РСБУ' and name == 'Рентабельность капитала (ROE)'\ngroup by month\norder by month",
     "round": "0s",
     "table": "finance_results"
    }
   ]
  }
 ]
}